# Replication Workflow

Single working notebook for the Segnon and Trede replication. Keep durable logic in `src/`; use this notebook for exploration, diagnostics, and figures.

In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd

from src import (
    # config
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    REPORTS_DIR,
    FIGURES_DIR,
    TABLES_DIR,
    ensure_project_dirs,

    # data
    load_price_csv,
    log_returns,
    align_return_frame,

    # statistics / backtesting
    summary_statistics,
    format_table_1,
    christoffersen_lr_test,
    violation_rate,

    # VaR v2 paper-like rolling functions
    SUPPORTED_COPULAS,
    RollingSpec,
    prepare_bivariate_returns,
    forecast_historical_var_rolling,
    forecast_variance_covariance_var_rolling,
    forecast_riskmetrics_var_rolling,
    forecast_ccc_garch_var_rolling,
    forecast_garch_copula_var_rolling,
    forecast_msm_copula_var_rolling,
    forecast_all_var_models,
    var_v2_portfolio_returns,
    var_v2_var_exceedances,
    violation_frequency,

    # plots
    plot_var_forecasts,
)

ensure_project_dirs()

## 1. Prices

In [2]:
raw_data_names = ["nasdaqcom_yahoo_close.csv", "sp500_yahoo_close.csv"]
raw_data_paths = [RAW_DATA_DIR / name for name in raw_data_names]

nasdaq_prices = load_price_csv(raw_data_paths[0])
sp500_prices = load_price_csv(raw_data_paths[1])
nasdaq_prices.name = "NASDAQ"
sp500_prices.name = "S&P 500"

prices = pd.concat(
    {
        "NASDAQ": nasdaq_prices,
        "S&P 500": sp500_prices,
    },
    axis=1,
).dropna()
prices.index.name = "date"

prices.head(), prices.tail(), prices.shape

(                 NASDAQ     S&P 500
 date
 2009-04-15  1626.800049  852.059998
 2009-04-16  1670.439941  865.299988
 2009-04-17  1673.069946  869.599976
 2009-04-20  1608.209961  832.390015
 2009-04-21  1643.849976  850.080017,
                  NASDAQ      S&P 500
 date
 2015-10-06  4748.359863  1979.920044
 2015-10-07  4791.149902  1995.829956
 2015-10-08  4810.790039  2013.430054
 2015-10-09  4830.470215  2014.890015
 2015-10-12  4838.640137  2017.459961,
 (1636, 2))

In [ ]:
#prices.to_csv(PROCESSED_DATA_DIR / "prices_nasdaq_sp500.csv")

In [4]:
fig1 = plot_price_evolution(
    prices,
    output_path=REPORTS_DIR / "figures" / "figure_1_prices.html",
)

fig1.show()

In [ ]:
#fig1.write_image(REPORTS_DIR / "figures" / "figure_1_prices.png", scale=2)

## 2. Build returns

In [3]:
returns = align_return_frame(
    {
        "NASDAQ": 100 * log_returns(prices["NASDAQ"]),
        "S&P 500": 100 * log_returns(prices["S&P 500"]),
    }
)
returns.head(), returns.tail(), returns.shape

(              NASDAQ   S&P 500
 date
 2009-04-16  2.647210  1.541931
 2009-04-17  0.157320  0.495705
 2009-04-20 -3.953850 -4.373221
 2009-04-21  2.191930  2.102938
 2009-04-22  0.137996 -0.771132,
               NASDAQ   S&P 500
 date
 2015-10-06 -0.690479 -0.359469
 2015-10-07  0.897118  0.800352
 2015-10-08  0.409087  0.877978
 2015-10-09  0.408250  0.072485
 2015-10-12  0.168990  0.127466,
 (1635, 2))

In [ ]:
#returns.to_csv(PROCESSED_DATA_DIR / "returns_nasdaq_sp500.csv")

In [8]:
fig2 = plot_returns_and_squared_returns(
    returns,
    output_path=REPORTS_DIR / "figures" / "figure_2_returns_squared_returns.html",
)

fig2.show()

In [ ]:
# fig2.write_image(
#     REPORTS_DIR / "figures" / "figure_2_returns_squared_returns.png",
#     scale=2,
# )

## 3. Descriptive Statistics

In [4]:
stats = summary_statistics(returns)
stats

,count,Mean,Std,Skewness,Kurtosis,Hurst,Tail index,Arch(1),Arch(1) p-value,Arch(5),Arch(5) p-value,Arch(10),Arch(10) p-value,JB,JB p-value,ADF,ADF p-value
NASDAQ,1635.0,0.066668,1.139080,-0.393170,6.025142,0.443318,3.852579,62.352988,2.870955e-15,243.573465,1.314607e-50,292.429966,6.185258e-57,660.180948,4.400770e-144,24.799764,0.0
S&P 500,1635.0,0.052718,1.035471,-0.429081,6.742166,0.435120,3.615215,69.899290,6.241092e-17,305.883788,5.439829e-64,345.043371,4.488230e-68,996.403046,4.303558e-217,20.273255,0.0

In [5]:
table_1 = format_table_1(stats)
table_1

,Mean,Std,Skewness,Kurtosis,Hurst,Tail index,Arch(1),Arch(5),Arch(10),JB,ADF
NASDAQ,0.067,1.139,-0.393,6.025,0.443,3.853,62.353 (0.000),243.573 (0.000),292.430 (0.000),660.181 (0.000),24.800 (0.000)
S&P 500,0.053,1.035,-0.429,6.742,0.435,3.615,69.899 (0.000),305.884 (0.000),345.043 (0.000),996.403 (0.000),20.273 (0.000)

- tail index: Hill est très sensible au seuil => actuellement fraction=0.5 donc 80 observ dans queues => le réduire ?
- écart sur ADF: peut-être du à diff de choix de lag (p-value à 0 donc même conclusion)

In [ ]:
#table_1.to_csv(REPORTS_DIR / "tables" / "table_1_statistics.csv", index=True)

Volatilité conditionnelle annuelle

In [17]:
float(float(table_1.loc['NASDAQ']['Std']) * np.sqrt(252)), float(float(table_1.loc['S&P 500']['Std']) * np.sqrt(252))

(18.081064459815412, 16.430115641711108)

## 4. MSM

runtime = 41min

In [6]:
msm_table = fit_msm_grid(
    returns=returns,
    k_values=range(1, 8),
    n_starts=30,
    seed=123,
)
msm_table

Estimating MSM: asset=NASDAQ, k=1, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2386.293, nit=9, nfev=70
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2386.293, nit=9, nfev=65
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2386.293, nit=10, nfev=65
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2386.293, nit=9, nfev=65
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2386.293, nit=11, nfev=70
  start 6/30: x0=[1.36645353 1.0272659  5.42513298 0.45135148]
    success=True, loglik=-2386.293, nit=14, nfev=135
  start 7/30: x0=[ 1.24072268  0.77442334 12.30695595  0.69617121]
    success=True, loglik=-2386.293, nit=16, nfev=125
  start 8/30: x0=[ 1.72943919  1.35872252 25.41418408  0.84695736]
    success=True, loglik=-2386.293, nit=12, nfev=115
  start 9/30: x0=[ 1.28724432  1.06036701 14.33466365  0.46915612]
    success=True, loglik=-2386.293, nit=12, nfev=95
  start 10/30: x0=[1.11855049 1.44069505 9.03265423 0.38509086]
    success=True, loglik=-2386.293, nit=11, nfev=80
  start 11/30: x0=[ 1.68806249  1.12358495 21.65883517  0.159983  ]
    success=True, loglik=-2386.293, nit=9, nfev=60
  start 12/30: x0=[ 1.23755399  1.75060457 20.37930386  0.3781446 ]
    success=True, loglik=-2386.293, nit=12, nfev=85
  start 13/30: x0=[ 1.43641688  0.80590685 19.36786614  0.63036821]
    success=True, loglik=-2386.293, nit=14, nfev=110
  start 14/30: x0=[ 1.21748899  1.41111603 15.56783226  0.04660262]
    success=True, loglik=-2386.293, nit=10, nfev=60
  start 15/30: x0=[ 1.24114022  1.70830693 27.70125023  0.74889763]
    success=True, loglik=-2386.293, nit=15, nfev=125
  start 16/30: x0=[ 1.20914817  1.09146669 25.89442798  0.24405999]
    success=True, loglik=-2386.293, nit=10, nfev=80
  start 17/30: x0=[ 1.52655359  1.44077481 25.88403124  0.22356772]
    success=True, loglik=-2386.293, nit=8, nfev=55
  start 18/30: x0=[ 1.54158297  1.41778836 24.25804919  0.69320875]
    success=True, loglik=-2386.293, nit=15, nfev=110
  start 19/30: x0=[ 1.27936064  1.63931186 15.72796371  0.61072975]
    success=True, loglik=-2386.293, nit=14, nfev=120
  start 20/30: x0=[1.73870415 1.70540617 8.99431307 0.02582111]
    success=True, loglik=-2386.293, nit=14, nfev=100
  start 21/30: x0=[ 1.70461233  0.75518111 29.91785279  0.83400037]
    success=True, loglik=-2386.293, nit=15, nfev=125
  start 22/30: x0=[ 1.64115004  1.43925915 18.33979682  0.19973985]
    success=True, loglik=-2386.293, nit=7, nfev=65
  start 23/30: x0=[1.77077907 1.12023455 9.49557678 0.83466105]
    success=True, loglik=-2386.293, nit=13, nfev=140
  start 24/30: x0=[1.48468376 1.67342591 4.74432851 0.60917957]
    success=True, loglik=-2386.293, nit=9, nfev=75
  start 25/30: x0=[1.35975518 0.91482828 4.03153533 0.46311231]
    success=True, loglik=-2386.293, nit=13, nfev=100
  start 26/30: x0=[ 1.3708647   1.54364769 22.99581788  0.15576975]
    success=True, loglik=-2386.293, nit=8, nfev=55
  start 27/30: x0=[1.71700129 1.53766706 9.32689348 0.60254755]
    success=True, loglik=-2386.293, nit=14, nfev=110
  start 28/30: x0=[1.56834655 1.16677879 1.59718638 0.71502876]
    success=True, loglik=-2386.293, nit=12, nfev=110
  start 29/30: x0=[ 1.48977022  1.20989899 15.54557932  0.63716212]
    success=True, loglik=-2392.777, nit=8, nfev=85
  start 30/30: x0=[ 1.48356016  0.79090748 13.60288864  0.19448562]
    success=True, loglik=-2386.293, nit=11, nfev=80
Estimating MSM: asset=NASDAQ, k=2, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2354.027, nit=19, nfev=130
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2355.996, nit=7, nfev=60
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2354.376, nit=7, nfev=60
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2354.375, nit=6, nfev=50
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2354.089, nit=8, nfev=60
  start 6/30: x0=[ 1.26227616  1.57708116 26.61863314  0.82051493]
    success=True, loglik=-2354.389, nit=11, nfev=85
  start 7/30: x0=[ 1.41184526  1.39240577 25.31535508  0.75206718]
    success=True, loglik=-2354.312, nit=13, nfev=105
  start 8/30: x0=[ 1.54243393  1.48244351 15.2641139   0.46834233]
    success=True, loglik=-2354.029, nit=10, nfev=80
  start 9/30: x0=[ 1.78342451  1.42289607 14.3602003   0.12511674]
    success=True, loglik=-2354.048, nit=9, nfev=70
  start 10/30: x0=[ 1.44686437  1.63795982 25.69295129  0.48025475]
    success=True, loglik=-2354.331, nit=10, nfev=65
  start 11/30: x0=[1.25070567 1.71689099 4.45615445 0.6917365 ]
    success=True, loglik=-2355.165, nit=8, nfev=75
  start 12/30: x0=[ 1.12930493  0.79196744 19.58469193  0.20412512]
    success=True, loglik=-2354.077, nit=10, nfev=70
  start 13/30: x0=[ 1.78774777  1.15167466 20.27538647  0.80933627]
    success=True, loglik=-2354.098, nit=11, nfev=110
  start 14/30: x0=[1.76664628 0.8424472  3.34401014 0.85346164]
    success=True, loglik=-2354.026, nit=25, nfev=185
  start 15/30: x0=[ 1.76744566  1.70968624 25.22924072  0.66927264]
    success=True, loglik=-2354.302, nit=12, nfev=130
  start 16/30: x0=[ 1.51353288  0.84058795 26.77713139  0.754737  ]
    success=True, loglik=-2354.382, nit=16, nfev=145
  start 17/30: x0=[ 1.76549844  1.23663039 27.939478    0.69324157]
    success=True, loglik=-2354.443, nit=12, nfev=90
  start 18/30: x0=[ 1.43634047  1.34899173 11.39424698  0.12851074]
    success=True, loglik=-2354.212, nit=5, nfev=40
  start 19/30: x0=[ 1.43263836  1.5306489  15.48527462  0.26277304]
    success=True, loglik=-2354.028, nit=8, nfev=60
  start 20/30: x0=[1.78831789 0.70508808 2.28327188 0.25456076]
    success=True, loglik=-2354.026, nit=20, nfev=130
  start 21/30: x0=[ 1.13450298  1.21872805 18.21389186  0.51546562]
    success=True, loglik=-2354.046, nit=13, nfev=85
  start 22/30: x0=[1.32429259 1.55989633 5.64891716 0.49036832]
    success=True, loglik=-2354.026, nit=21, nfev=145
  start 23/30: x0=[ 1.39467855  1.70334694 10.63141605  0.23690776]
    success=True, loglik=-2354.265, nit=6, nfev=40
  start 24/30: x0=[1.69335319 0.98634846 1.68139138 0.19508113]
    success=True, loglik=-2359.332, nit=6, nfev=55
  start 25/30: x0=[ 1.7698207   1.27720666 12.37420204  0.7309071 ]
    success=True, loglik=-2354.133, nit=11, nfev=100
  start 26/30: x0=[ 1.37508089  1.05978013 21.99837837  0.91646063]
    success=True, loglik=-2354.160, nit=14, nfev=110
  start 27/30: x0=[ 1.40105303  1.46963664 28.72337215  0.68406919]
    success=True, loglik=-2354.492, nit=14, nfev=80
  start 28/30: x0=[1.65017116 1.62392928 5.70963463 0.04534393]
    success=True, loglik=-2355.622, nit=10, nfev=65
  start 29/30: x0=[ 1.40180308  1.61829476 29.1659578   0.31658285]
    success=True, loglik=-2354.511, nit=8, nfev=50
  start 30/30: x0=[1.2991777  0.94257407 9.17315948 0.1250602 ]
    success=True, loglik=-2354.513, nit=9, nfev=65
Estimating MSM: asset=NASDAQ, k=3, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2355.671, nit=4, nfev=35
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2353.842, nit=8, nfev=65
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.813, nit=10, nfev=90
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2355.792, nit=6, nfev=60
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2354.930, nit=7, nfev=75
  start 6/30: x0=[ 1.56707059  0.83413026 16.83123446  0.26317655]
    success=True, loglik=-2355.095, nit=8, nfev=75
  start 7/30: x0=[ 1.7784379   1.75860711 19.24426587  0.40345076]
    success=True, loglik=-2354.911, nit=11, nfev=100
  start 8/30: x0=[ 1.63070993  1.30957437 22.82297117  0.42714658]
    success=True, loglik=-2349.787, nit=12, nfev=95
  start 9/30: x0=[1.18607674 1.66172423 6.19442008 0.27299112]
    success=True, loglik=-2349.760, nit=25, nfev=170
  start 10/30: x0=[ 1.7680076   1.10422557 24.70445744  0.51173545]
    success=True, loglik=-2355.180, nit=13, nfev=90
  start 11/30: x0=[ 1.17240342  1.13839283 15.4618717   0.852756  ]
    success=True, loglik=-2350.055, nit=9, nfev=55
  start 12/30: x0=[ 1.32706561  1.16853726 11.03677905  0.24594379]
    success=True, loglik=-2351.060, nit=10, nfev=75
  start 13/30: x0=[ 1.45472538  1.52160908 20.34009861  0.54580526]
    success=True, loglik=-2349.762, nit=12, nfev=105
  start 14/30: x0=[ 1.25177869  1.07385995 20.29127276  0.68044328]
    success=True, loglik=-2349.762, nit=10, nfev=75
  start 15/30: x0=[ 1.49720326  1.4938389  10.96344286  0.71060358]
    success=True, loglik=-2351.042, nit=8, nfev=55
  start 16/30: x0=[1.19278411 0.77375097 2.78620884 0.34955106]
    success=True, loglik=-2349.760, nit=26, nfev=180
  start 17/30: x0=[ 1.36024877  0.89659309 15.20475557  0.07082706]
    success=True, loglik=-2354.870, nit=7, nfev=55
  start 18/30: x0=[ 1.22134301  1.51869357 28.50391758  0.33328393]
    success=True, loglik=-2355.334, nit=6, nfev=40
  start 19/30: x0=[1.20544475 0.7347534  2.73583487 0.0675015 ]
    success=True, loglik=-2354.187, nit=29, nfev=195
  start 20/30: x0=[ 1.47833369  0.7028916  27.12939719  0.26467321]
    success=True, loglik=-2355.189, nit=18, nfev=170
  start 21/30: x0=[1.31109678 1.62331135 2.04692317 0.26251572]
    success=True, loglik=-2355.068, nit=14, nfev=80
  start 22/30: x0=[ 1.53003963  1.55962262 28.85742788  0.85116455]
    success=True, loglik=-2350.096, nit=9, nfev=65
  start 23/30: x0=[ 1.36649656  1.53056946 24.10354128  0.55829255]
    success=True, loglik=-2355.163, nit=7, nfev=55
  start 24/30: x0=[ 1.43764048  1.17451573 28.53160815  0.70997449]
    success=True, loglik=-2350.074, nit=10, nfev=90
  start 25/30: x0=[ 1.35098199  1.60943599 11.84493962  0.87217749]
    success=True, loglik=-2350.647, nit=8, nfev=65
  start 26/30: x0=[ 1.53962563  0.99343265 14.6774041   0.30881411]
    success=True, loglik=-2354.832, nit=9, nfev=80
  start 27/30: x0=[1.72432382 0.77672639 8.37713317 0.29270062]
    success=True, loglik=-2356.197, nit=10, nfev=75
  start 28/30: x0=[ 1.52113177  1.70794267 17.95313686  0.55752705]
    success=True, loglik=-2349.832, nit=12, nfev=100
  start 29/30: x0=[1.4753187  1.24291297 5.707742   0.56322883]
    success=True, loglik=-2353.474, nit=7, nfev=65
  start 30/30: x0=[ 1.47425619  1.23103145 29.69344658  0.22977511]
    success=True, loglik=-2355.387, nit=9, nfev=70
Estimating MSM: asset=NASDAQ, k=4, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2352.998, nit=17, nfev=130
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2355.521, nit=8, nfev=60
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.000, nit=8, nfev=70
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2352.802, nit=7, nfev=50
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2358.369, nit=5, nfev=35
  start 6/30: x0=[ 1.28397304  0.90295364 12.45678332  0.8752744 ]
    success=True, loglik=-2351.797, nit=12, nfev=100
  start 7/30: x0=[ 1.49426394  1.0675174  20.82991147  0.43306032]
    success=True, loglik=-2350.651, nit=12, nfev=135
  start 8/30: x0=[ 1.36197541  1.64746442 10.65407716  0.46632752]
    success=True, loglik=-2352.475, nit=11, nfev=90
  start 9/30: x0=[ 1.52577169  1.04226165 27.00396377  0.55599156]
    success=True, loglik=-2350.790, nit=12, nfev=135
  start 10/30: x0=[1.63161316 1.44032634 8.99793903 0.5832572 ]
    success=True, loglik=-2353.264, nit=10, nfev=105
  start 11/30: x0=[ 1.62010768  1.35762559 10.35859344  0.10766128]
    success=True, loglik=-2354.843, nit=8, nfev=75
  start 12/30: x0=[ 1.6182472   1.20359562 20.93313567  0.66084184]
    success=True, loglik=-2350.559, nit=11, nfev=90
  start 13/30: x0=[ 1.14743692  0.88736116 11.3719921   0.27433615]
    success=True, loglik=-2355.111, nit=20, nfev=175
  start 14/30: x0=[1.42498181 1.15229956 2.69429424 0.37143879]
    success=True, loglik=-2353.007, nit=11, nfev=85
  start 15/30: x0=[ 1.30153634  1.60998307 10.81690609  0.68975644]
    success=True, loglik=-2352.291, nit=8, nfev=50
  start 16/30: x0=[ 1.34712201  0.93542279 16.75371585  0.02894012]
    success=True, loglik=-2355.815, nit=7, nfev=50
  start 17/30: x0=[ 1.49483524  1.15086943 25.65355193  0.18921568]
    success=True, loglik=-2355.172, nit=11, nfev=70
  start 18/30: x0=[ 1.33992201  0.68444251 28.76257893  0.11106781]
    success=True, loglik=-2355.965, nit=13, nfev=100
  start 19/30: x0=[ 1.64145876  1.31813157 29.86358139  0.84452534]
    success=True, loglik=-2350.959, nit=11, nfev=90
  start 20/30: x0=[ 1.10131917  1.25212172 25.89863027  0.92788729]
    success=True, loglik=-2350.737, nit=12, nfev=75
  start 21/30: x0=[ 1.7372881   1.42616467 11.88822987  0.59626468]
    success=True, loglik=-2351.996, nit=10, nfev=90
  start 22/30: x0=[1.10251998 1.71099298 7.43334032 0.6877691 ]
    success=True, loglik=-2350.642, nit=24, nfev=150
  start 23/30: x0=[1.25624873 1.57606748 6.97170725 0.91904366]
    success=True, loglik=-2350.648, nit=17, nfev=100
  start 24/30: x0=[ 1.70679999  1.58075273 13.95285071  0.2073811 ]
    success=True, loglik=-2355.074, nit=9, nfev=70
  start 25/30: x0=[1.61523418 1.01126042 2.26572299 0.29414558]
    success=True, loglik=-2353.013, nit=13, nfev=110
  start 26/30: x0=[1.41986225 1.05729164 9.38318033 0.25008439]
    success=True, loglik=-2356.718, nit=6, nfev=95
  start 27/30: x0=[ 1.47593211  1.45675377 10.69057919  0.87900828]
    success=True, loglik=-2352.412, nit=8, nfev=60
  start 28/30: x0=[ 1.36487873  1.07121623 10.84662727  0.45210435]
    success=True, loglik=-2352.414, nit=8, nfev=55
  start 29/30: x0=[ 1.40916985  1.05474878 11.2228337   0.91247365]
    success=True, loglik=-2352.112, nit=9, nfev=95
  start 30/30: x0=[ 1.44142311  1.13245414 11.5168451   0.57002104]
    success=True, loglik=-2352.126, nit=8, nfev=55
Estimating MSM: asset=NASDAQ, k=5, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2352.691, nit=17, nfev=110
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2353.886, nit=10, nfev=80
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.485, nit=7, nfev=60
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2355.486, nit=7, nfev=50
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2355.321, nit=14, nfev=130
  start 6/30: x0=[ 1.6247279   1.49507416 13.79808988  0.86015646]
    success=True, loglik=-2351.368, nit=9, nfev=65
  start 7/30: x0=[ 1.21538983  1.78036171 13.34161962  0.3494575 ]
    success=True, loglik=-2355.466, nit=12, nfev=110
  start 8/30: x0=[1.62090539 1.10632279 8.12616137 0.88104693]
    success=True, loglik=-2354.262, nit=9, nfev=95
  start 9/30: x0=[ 1.74166138  1.07819664 16.16543633  0.80811075]
    success=True, loglik=-2351.696, nit=10, nfev=80
  start 10/30: x0=[1.56115621 0.86260559 3.64937555 0.41022691]
    success=True, loglik=-2352.967, nit=12, nfev=100
  start 11/30: x0=[ 1.76904087  0.87337506 10.49792737  0.64224144]
    success=True, loglik=-2353.175, nit=10, nfev=70
  start 12/30: x0=[ 1.72474374  1.20435311 21.08751172  0.68050503]
    success=True, loglik=-2351.256, nit=13, nfev=100
  start 13/30: x0=[ 1.46629102  0.72425118 15.1129546   0.12452641]
    success=True, loglik=-2356.583, nit=6, nfev=45
  start 14/30: x0=[1.13536966e+00 8.22082741e-01 2.54644227e+01 2.21816867e-02]
    success=True, loglik=-2355.437, nit=15, nfev=110
  start 15/30: x0=[ 1.42570983  1.76765383 22.19399926  0.40779364]
    success=True, loglik=-2351.254, nit=10, nfev=100
  start 16/30: x0=[ 1.20837769  1.31679225 12.70120784  0.40568761]
    success=True, loglik=-2352.572, nit=8, nfev=60
  start 17/30: x0=[ 1.16208397  1.03100944 15.14015658  0.70019369]
    success=True, loglik=-2356.274, nit=11, nfev=140
  start 18/30: x0=[ 1.59067141  1.43896171 27.62217627  0.89279488]
    success=True, loglik=-2350.791, nit=7, nfev=65
  start 19/30: x0=[ 1.52221392  1.74849789 15.58407473  0.32849268]
    success=True, loglik=-2355.269, nit=16, nfev=115
  start 20/30: x0=[ 1.20881406  1.01369736 19.21755346  0.39282413]
    success=True, loglik=-2351.292, nit=20, nfev=150
  start 21/30: x0=[ 1.41810592  0.8498853  22.94348011  0.1170697 ]
    success=True, loglik=-2356.524, nit=9, nfev=75
  start 22/30: x0=[ 1.60749837  1.62795123 28.87132061  0.3707014 ]
    success=True, loglik=-2355.616, nit=8, nfev=65
  start 23/30: x0=[ 1.40181178  1.38937649 26.952324    0.86947131]
    success=True, loglik=-2351.482, nit=7, nfev=55
  start 24/30: x0=[ 1.72303769  0.92702936 14.88785876  0.47172749]
    success=True, loglik=-2351.909, nit=10, nfev=65
  start 25/30: x0=[ 1.2139393   0.90780257 17.34323283  0.53364468]
    success=True, loglik=-2351.446, nit=12, nfev=100
  start 26/30: x0=[ 1.40998509  1.16867446 20.26485253  0.515693  ]
    success=True, loglik=-2350.626, nit=12, nfev=80
  start 27/30: x0=[ 1.12147761  1.01549881 13.30594734  0.25490355]
    success=True, loglik=-2356.023, nit=12, nfev=100
  start 28/30: x0=[ 1.59091343  1.09124583 23.45009885  0.58163866]
    success=True, loglik=-2351.358, nit=11, nfev=100
  start 29/30: x0=[ 1.76164315  0.70612263 24.62756553  0.45505822]
    success=True, loglik=-2356.573, nit=11, nfev=80
  start 30/30: x0=[ 1.42469317  1.4592055  13.0938377   0.03931374]
    success=True, loglik=-2355.227, nit=11, nfev=80
Estimating MSM: asset=NASDAQ, k=6, n_starts=30
  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2352.457, nit=17, nfev=125
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2354.571, nit=8, nfev=65
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.146, nit=10, nfev=90
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2356.166, nit=9, nfev=70
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2355.740, nit=13, nfev=105
  start 6/30: x0=[ 1.75655119  0.99010864 27.72142663  0.94941249]
    success=True, loglik=-2352.219, nit=11, nfev=100
  start 7/30: x0=[ 1.54496275  0.83816974 17.5854284   0.27166892]
    success=True, loglik=-2355.744, nit=11, nfev=75
  start 8/30: x0=[ 1.50259334  0.77159436 10.04650223  0.55746284]
    success=True, loglik=-2354.208, nit=8, nfev=60
  start 9/30: x0=[ 1.42244447  1.19662713 28.85896216  0.6788465 ]
    success=True, loglik=-2351.161, nit=11, nfev=95
  start 10/30: x0=[ 1.69660337  1.30796912 24.96145344  0.91396685]
    success=True, loglik=-2350.944, nit=9, nfev=100
  start 11/30: x0=[ 1.76435055  1.6988064  15.41379315  0.63211452]
    success=True, loglik=-2351.321, nit=11, nfev=80
  start 12/30: x0=[1.15371828 1.29088465 6.27606531 0.8868234 ]
    success=True, loglik=-2353.775, nit=21, nfev=160
  start 13/30: x0=[ 1.16054038  1.13902888 22.65868524  0.77957413]
    success=True, loglik=-2352.038, nit=9, nfev=60
  start 14/30: x0=[1.37749067 1.4073392  9.76175129 0.36737992]
    success=True, loglik=-2354.153, nit=12, nfev=90
  start 15/30: x0=[1.41779103 1.24970818 3.57432225 0.82111723]
    success=True, loglik=-2352.756, nit=11, nfev=70
  start 16/30: x0=[ 1.58036247  1.33178031 12.56577288  0.58573361]
    success=True, loglik=-2352.027, nit=8, nfev=60

,asset,k,mean_return,m0,sigma,b,gamma_1,gamma_k,log_likelihood,success,message,nobs
0,NASDAQ,1,0.066668,1.626379,1.304680,2.000000,4.091375e-02,0.040914,-2386.292750,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
1,NASDAQ,2,0.066668,1.549589,1.343466,16.260779,8.891087e-03,0.135170,-2354.025612,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
2,NASDAQ,3,0.066668,1.512055,1.334460,20.799781,5.595557e-03,0.911752,-2349.759985,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
3,NASDAQ,4,0.066668,1.511582,1.908756,20.890437,2.643599e-04,0.910224,-2350.558626,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
4,NASDAQ,5,0.066668,1.511223,1.551741,20.140847,1.407945e-05,0.901417,-2350.625955,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
5,NASDAQ,6,0.066668,1.512051,2.224445,21.717327,5.189026e-07,0.918470,-2350.876234,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
6,NASDAQ,7,0.066668,1.512521,1.811152,22.540539,1.981866e-08,0.925676,-2350.894984,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
7,S&P 500,1,0.052718,1.701427,1.097393,20.379304,7.262538e-02,0.072625,-2183.472284,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
8,S&P 500,2,0.052718,1.594092,1.227832,14.420167,8.744065e-03,0.118954,-2136.246971,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
9,S&P 500,3,0.052718,1.549599,1.220385,23.750954,4.598325e-03,0.925721,-2134.752201,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
10,S&P 500,4,0.052718,1.549782,0.980843,24.702648,1.781063e-04,0.931781,-2135.584183,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
11,S&P 500,5,0.052718,1.550183,1.462294,27.619572,5.125927e-06,0.949355,-2135.597714,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
12,S&P 500,6,0.052718,1.549809,2.178529,25.012387,2.776267e-07,0.933988,-2135.823087,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635
13,S&P 500,7,0.052718,1.550197,3.252207,26.667435,8.024165e-09,0.944198,-2136.246669,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,1635

In [7]:
loglik_pivot = msm_table.pivot(
    index="asset",
    columns="k",
    values="log_likelihood",
)

loglik_pivot

k,1,2,3,4,5,6,7
asset,,,,,,,
NASDAQ,-2386.292750,-2354.025612,-2349.759985,-2350.558626,-2350.625955,-2350.876234,-2350.894984
S&P 500,-2183.472284,-2136.246971,-2134.752201,-2135.584183,-2135.597714,-2135.823087,-2136.246669

In [8]:
for param in ["m0", "sigma", "b", "gamma_k"]:
    display(
        msm_table.pivot(
            index="asset",
            columns="k",
            values=param,
        )
    )

k               1         2         3         4         5         6         7
asset
NASDAQ   1.626379  1.549589  1.512055  1.511582  1.511223  1.512051  1.512521
S&P 500  1.701427  1.594092  1.549599  1.549782  1.550183  1.549809  1.550197

k               1         2         3         4         5         6         7
asset
NASDAQ   1.304680  1.343466  1.334460  1.908756  1.551741  2.224445  1.811152
S&P 500  1.097393  1.227832  1.220385  0.980843  1.462294  2.178529  3.252207

k,1,2,3,4,5,6,7
asset,,,,,,,
NASDAQ,2.000000,16.260779,20.799781,20.890437,20.140847,21.717327,22.540539
S&P 500,20.379304,14.420167,23.750954,24.702648,27.619572,25.012387,26.667435

k               1         2         3         4         5         6         7
asset
NASDAQ   0.040914  0.135170  0.911752  0.910224  0.901417  0.918470  0.925676
S&P 500  0.072625  0.118954  0.925721  0.931781  0.949355  0.933988  0.944198

In [ ]:
#msm_table.to_csv(REPORTS_DIR / "tables" / "table_2_msm_estimates_raw.csv", index=False)

In [ ]:
msm_table = pd.read_csv(REPORTS_DIR / "tables" / "table_2_msm_estimates_raw.csv")

best k:
- NASDAQ = 3
- SP500 = 3

papier: SP500 best k = 4

### k=3 & k=4

we use the selected k in the paper

In [24]:
%%time

res_nasdaq_final = fit_msm(
    returns=returns["NASDAQ"],
    k=3,
    n_starts=30,
    seed=123,
)

res_sp500_final = fit_msm(
    returns=returns["S&P 500"],
    k=4,
    n_starts=30,
    seed=123,
)

  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2355.671, nit=4, nfev=35
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2353.842, nit=8, nfev=65
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.813, nit=10, nfev=90
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2355.792, nit=6, nfev=60
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2354.930, nit=7, nfev=75
  start 6/30: x0=[1.5776463  0.74475455 7.54636434 0.19146578]
    success=True, loglik=-2354.246, nit=10, nfev=85
  start 7/30: x0=[ 1.22313413  1.60848884 27.79233594  0.27721419]
    success=True, loglik=-2355.302, nit=6, nfev=40
  start 8/30: x0=[ 1.67382819  1.69710722 15.97354911  0.24781708]
    success=True, loglik=-2354.873, nit=12, nfev=100
  start 9/30: x0=[ 1.67696912  0.92694125 22.5542511   0.60584439]
    success=True, loglik=-2349.783, nit=13, nfev=125
  start 10/30: x0=[ 1.74918508  0.94761012 24.2148037   0.50189348]
    success=True, loglik=-2355.163, nit=10, nfev=75
  start 11/30: x0=[ 1.26208894  0.87242605 15.53632229  0.56193392]
    success=True, loglik=-2350.048, nit=10, nfev=85
  start 12/30: x0=[ 1.22903659  0.7004146  14.76863699  0.6972663 ]
    success=True, loglik=-2354.864, nit=17, nfev=110
  start 13/30: x0=[ 1.74302034  1.39598148 27.61313009  0.82416193]
    success=True, loglik=-2350.016, nit=9, nfev=80
  start 14/30: x0=[ 1.25270001  1.67003668 22.24565577  0.27841472]
    success=True, loglik=-2355.108, nit=6, nfev=40
  start 15/30: x0=[1.65793049 1.66900499 9.82381139 0.51014914]
    success=True, loglik=-2351.499, nit=10, nfev=80
  start 16/30: x0=[1.15004076 1.3478034  8.05170431 0.73141619]
    success=True, loglik=-2349.760, nit=20, nfev=145
  start 17/30: x0=[1.22154215 1.0396866  1.61686493 0.05027329]
    success=True, loglik=-2356.022, nit=12, nfev=85
  start 18/30: x0=[1.44769129 1.21689362 4.8774813  0.25953313]
    success=True, loglik=-2353.902, nit=3, nfev=40
  start 19/30: x0=[ 1.10222678  1.11751481 17.78514482  0.41738786]
    success=True, loglik=-2354.889, nit=8, nfev=60
  start 20/30: x0=[1.68457164 1.38568106 8.86321667 0.77425056]
    success=True, loglik=-2351.914, nit=9, nfev=60
  start 21/30: x0=[ 1.44964073  1.54779389 17.50336569  0.42681954]
    success=True, loglik=-2355.080, nit=8, nfev=65
  start 22/30: x0=[ 1.37730811  0.70877587 14.7173027   0.59990931]
    success=True, loglik=-2354.846, nit=15, nfev=105
  start 23/30: x0=[ 1.76227939  1.1793194  15.18647241  0.50277708]
    success=True, loglik=-2355.160, nit=12, nfev=100
  start 24/30: x0=[1.38601369 1.34274282 3.22609939 0.47419696]
    success=True, loglik=-2355.068, nit=18, nfev=115
  start 25/30: x0=[ 1.52710138  1.53078604 13.57911323  0.30160598]
    success=True, loglik=-2354.662, nit=11, nfev=85
  start 26/30: x0=[1.10412302 1.54513829 3.43418794 0.47568888]
    success=True, loglik=-2349.760, nit=21, nfev=130
  start 27/30: x0=[ 1.31305277  1.64121195 28.57370483  0.31655336]
    success=True, loglik=-2355.337, nit=6, nfev=45
  start 28/30: x0=[ 1.7284378   1.06792075 24.58882878  0.76292455]
    success=True, loglik=-2349.834, nit=18, nfev=210
  start 29/30: x0=[1.55869962 0.94395967 5.16502458 0.41466516]
    success=True, loglik=-2353.711, nit=8, nfev=65
  start 30/30: x0=[1.20607713 1.67817599 6.35885062 0.04817404]
    success=True, loglik=-2356.608, nit=9, nfev=60
  start 1/30: x0=[1.5        1.03547075 2.         0.1       ]
    success=True, loglik=-2136.987, nit=9, nfev=90
  start 2/30: x0=[1.5        1.03547075 5.         0.2       ]
    success=True, loglik=-2140.101, nit=12, nfev=100
  start 3/30: x0=[ 1.4         1.03547075 10.          0.1       ]
    success=True, loglik=-2137.485, nit=11, nfev=95
  start 4/30: x0=[ 1.6         1.03547075 10.          0.2       ]
    success=True, loglik=-2135.584, nit=23, nfev=140
  start 5/30: x0=[ 1.3         1.03547075 20.          0.1       ]
    success=True, loglik=-2137.312, nit=9, nfev=90
  start 6/30: x0=[1.5776463  0.67701254 7.54636434 0.19146578]
    success=True, loglik=-2137.337, nit=10, nfev=100
  start 7/30: x0=[ 1.22313413  1.46218256 27.79233594  0.27721419]
    success=True, loglik=-2137.759, nit=10, nfev=85
  start 8/30: x0=[ 1.67382819  1.54274031 15.97354911  0.24781708]
    success=True, loglik=-2137.220, nit=10, nfev=65
  start 9/30: x0=[ 1.67696912  0.84262775 22.5542511   0.60584439]
    success=True, loglik=-2135.616, nit=10, nfev=90
  start 10/30: x0=[ 1.74918508  0.8614166  24.2148037   0.50189348]
    success=True, loglik=-2138.283, nit=11, nfev=105
  start 11/30: x0=[ 1.26208894  0.79307119 15.53632229  0.56193392]
    success=True, loglik=-2136.443, nit=11, nfev=115
  start 12/30: x0=[ 1.22903659  0.6367057  14.76863699  0.6972663 ]
    success=True, loglik=-2136.626, nit=13, nfev=80
  start 13/30: x0=[ 1.74302034  1.26900462 27.61313009  0.82416193]
    success=True, loglik=-2135.631, nit=7, nfev=50
  start 14/30: x0=[ 1.25270001  1.51813208 22.24565577  0.27841472]
    success=True, loglik=-2137.418, nit=11, nfev=75
  start 15/30: x0=[1.65793049 1.51719423 9.82381139 0.51014914]
    success=True, loglik=-2135.505, nit=25, nfev=160
  start 16/30: x0=[1.15004076 1.22520877 8.05170431 0.73141619]
    success=True, loglik=-2135.584, nit=22, nfev=130
  start 17/30: x0=[1.22154215 0.94511791 1.61686493 0.05027329]
    success=True, loglik=-2136.321, nit=17, nfev=115
  start 18/30: x0=[1.44769129 1.10620639 4.8774813  0.25953313]
    success=True, loglik=-2137.028, nit=11, nfev=125
  start 19/30: x0=[ 1.10222678  1.01586696 17.78514482  0.41738786]
    success=True, loglik=-2138.037, nit=11, nfev=80
  start 20/30: x0=[1.68457164 1.25964111 8.86321667 0.77425056]
    success=True, loglik=-2138.976, nit=11, nfev=80
  start 21/30: x0=[ 1.44964073  1.40700835 17.50336569  0.42681954]
    success=True, loglik=-2135.952, nit=11, nfev=80
  start 22/30: x0=[ 1.37730811  0.64430644 14.7173027   0.59990931]
    success=True, loglik=-2137.785, nit=16, nfev=100
  start 23/30: x0=[ 1.76227939  1.07204988 15.18647241  0.50277708]
    success=True, loglik=-2136.517, nit=9, nfev=65
  start 24/30: x0=[1.38601369 1.22060849 3.22609939 0.47419696]
    success=True, loglik=-2136.321, nit=17, nfev=135
  start 25/30: x0=[ 1.52710138  1.39154751 13.57911323  0.30160598]
    success=True, loglik=-2137.255, nit=9, nfev=100
  start 26/30: x0=[1.10412302 1.4045943  3.43418794 0.47568888]
    success=True, loglik=-2135.584, nit=19, nfev=110
  start 27/30: x0=[ 1.31305277  1.49192921 28.57370483  0.31655336]
    success=True, loglik=-2137.812, nit=11, nfev=90
  start 28/30: x0=[ 1.7284378   0.97078391 24.58882878  0.76292455]
    success=True, loglik=-2135.584, nit=10, nfev=65
  start 29/30: x0=[1.55869962 0.85809819 5.16502458 0.41466516]
    success=True, loglik=-2141.106, nit=5, nfev=45
  start 30/30: x0=[1.20607713 1.52553105 6.35885062 0.04817404]
    success=True, loglik=-2140.858, nit=12, nfev=75
CPU times: user 4min 9s, sys: 3.51 s, total: 4min 13s
Wall time: 4min 22s

In [25]:
msm_fit_results = {
    "NASDAQ": res_nasdaq_final,
    "S&P 500": res_sp500_final,
}

In [26]:
pit_msm = build_msm_pit_frame(
    returns=returns,
    fit_results=msm_fit_results,
)

pit_msm.head()

              NASDAQ   S&P 500
date
2009-04-16  0.968529  0.862457
2009-04-17  0.527258  0.635519
2009-04-20  0.011079  0.011669
2009-04-21  0.881390  0.838473
2009-04-22  0.517535  0.330242

In [ ]:
#pit_msm.to_csv(PROCESSED_DATA_DIR / "pit_msm.csv")

In [13]:
pit_msm = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_msm.csv",
    index_col="date",
    parse_dates=True,
)

### k=3

testing with empirical results

In [27]:
res_sp500_emp = fit_msm(
    returns=returns["S&P 500"],
    k=3,
    n_starts=30,
    seed=123,
)

  start 1/30: x0=[1.5        1.03547075 2.         0.1       ]
    success=True, loglik=-2139.144, nit=12, nfev=85
  start 2/30: x0=[1.5        1.03547075 5.         0.2       ]
    success=True, loglik=-2140.102, nit=7, nfev=60
  start 3/30: x0=[ 1.4         1.03547075 10.          0.1       ]
    success=True, loglik=-2136.720, nit=10, nfev=65
  start 4/30: x0=[ 1.6         1.03547075 10.          0.2       ]
    success=True, loglik=-2137.886, nit=7, nfev=65
  start 5/30: x0=[ 1.3         1.03547075 20.          0.1       ]
    success=True, loglik=-2134.866, nit=11, nfev=105
  start 6/30: x0=[1.5776463  0.67701254 7.54636434 0.19146578]
    success=True, loglik=-2136.834, nit=10, nfev=95
  start 7/30: x0=[ 1.22313413  1.46218256 27.79233594  0.27721419]
    success=True, loglik=-2137.798, nit=8, nfev=60
  start 8/30: x0=[ 1.67382819  1.54274031 15.97354911  0.24781708]
    success=True, loglik=-2137.092, nit=10, nfev=95
  start 9/30: x0=[ 1.67696912  0.84262775 22.5542511   0.60584439]
    success=True, loglik=-2134.763, nit=13, nfev=95
  start 10/30: x0=[ 1.74918508  0.8614166  24.2148037   0.50189348]
    success=True, loglik=-2137.577, nit=12, nfev=120
  start 11/30: x0=[ 1.26208894  0.79307119 15.53632229  0.56193392]
    success=True, loglik=-2135.426, nit=12, nfev=85
  start 12/30: x0=[ 1.22903659  0.6367057  14.76863699  0.6972663 ]
    success=True, loglik=-2135.577, nit=11, nfev=65
  start 13/30: x0=[ 1.74302034  1.26900462 27.61313009  0.82416193]
    success=True, loglik=-2134.831, nit=10, nfev=80
  start 14/30: x0=[ 1.25270001  1.51813208 22.24565577  0.27841472]
    success=True, loglik=-2137.474, nit=6, nfev=55
  start 15/30: x0=[1.65793049 1.51719423 9.82381139 0.51014914]
    success=True, loglik=-2137.373, nit=13, nfev=80
  start 16/30: x0=[1.15004076 1.22520877 8.05170431 0.73141619]
    success=True, loglik=-2134.752, nit=25, nfev=150
  start 17/30: x0=[1.22154215 0.94511791 1.61686493 0.05027329]
    success=True, loglik=-2139.631, nit=12, nfev=85
  start 18/30: x0=[1.44769129 1.10620639 4.8774813  0.25953313]
    success=True, loglik=-2140.137, nit=7, nfev=50
  start 19/30: x0=[ 1.10222678  1.01586696 17.78514482  0.41738786]
    success=True, loglik=-2137.326, nit=11, nfev=95
  start 20/30: x0=[1.68457164 1.25964111 8.86321667 0.77425056]
    success=True, loglik=-2134.752, nit=20, nfev=120
  start 21/30: x0=[ 1.44964073  1.40700835 17.50336569  0.42681954]
    success=True, loglik=-2137.323, nit=8, nfev=60
  start 22/30: x0=[ 1.37730811  0.64430644 14.7173027   0.59990931]
    success=True, loglik=-2135.596, nit=12, nfev=85
  start 23/30: x0=[ 1.76227939  1.07204988 15.18647241  0.50277708]
    success=True, loglik=-2137.342, nit=16, nfev=140
  start 24/30: x0=[1.38601369 1.22060849 3.22609939 0.47419696]
    success=True, loglik=-2137.320, nit=17, nfev=105
  start 25/30: x0=[ 1.52710138  1.39154751 13.57911323  0.30160598]
    success=True, loglik=-2137.037, nit=13, nfev=90
  start 26/30: x0=[1.10412302 1.4045943  3.43418794 0.47568888]
    success=True, loglik=-2134.752, nit=22, nfev=135
  start 27/30: x0=[ 1.31305277  1.49192921 28.57370483  0.31655336]
    success=True, loglik=-2137.851, nit=7, nfev=55
  start 28/30: x0=[ 1.7284378   0.97078391 24.58882878  0.76292455]
    success=True, loglik=-2134.756, nit=12, nfev=85
  start 29/30: x0=[1.55869962 0.85809819 5.16502458 0.41466516]
    success=True, loglik=-2134.758, nit=19, nfev=135
  start 30/30: x0=[1.20607713 1.52553105 6.35885062 0.04817404]
    success=True, loglik=-2138.976, nit=10, nfev=65

In [ ]:
msm_fit_results_emp = {
    "NASDAQ": res_nasdaq_final,
    "S&P 500": res_sp500_emp,
}
pit_msm_emp = build_msm_pit_frame(
    returns=returns,
    fit_results=msm_fit_results_emp,
)
#pit_msm_emp.to_csv(PROCESSED_DATA_DIR / "pit_msm_emp.csv")

In [14]:
pit_msm_emp = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_msm_emp.csv",
    index_col="date",
    parse_dates=True,
)

### k=5

runtime = 4min

In [14]:
%%time

res_nasdaq_5 = fit_msm(
    returns=returns["NASDAQ"],
    k=5,
    n_starts=30,
    seed=123,
)

res_sp500_5 = fit_msm(
    returns=returns["S&P 500"],
    k=5,
    n_starts=30,
    seed=123,
)

  start 1/30: x0=[1.5        1.13908017 2.         0.1       ]
    success=True, loglik=-2352.691, nit=17, nfev=110
  start 2/30: x0=[1.5        1.13908017 5.         0.2       ]
    success=True, loglik=-2353.886, nit=10, nfev=80
  start 3/30: x0=[ 1.4         1.13908017 10.          0.1       ]
    success=True, loglik=-2355.485, nit=7, nfev=60
  start 4/30: x0=[ 1.6         1.13908017 10.          0.2       ]
    success=True, loglik=-2355.486, nit=7, nfev=50
  start 5/30: x0=[ 1.3         1.13908017 20.          0.1       ]
    success=True, loglik=-2355.321, nit=14, nfev=130
  start 6/30: x0=[1.5776463  0.74475455 7.54636434 0.19146578]
    success=True, loglik=-2358.019, nit=9, nfev=70
  start 7/30: x0=[ 1.22313413  1.60848884 27.79233594  0.27721419]
    success=True, loglik=-2355.565, nit=10, nfev=60
  start 8/30: x0=[ 1.67382819  1.69710722 15.97354911  0.24781708]
    success=True, loglik=-2350.959, nit=10, nfev=95
  start 9/30: x0=[ 1.67696912  0.92694125 22.5542511   0.60584439]
    success=True, loglik=-2351.345, nit=9, nfev=70
  start 10/30: x0=[ 1.74918508  0.94761012 24.2148037   0.50189348]
    success=True, loglik=-2351.376, nit=12, nfev=100
  start 11/30: x0=[ 1.26208894  0.87242605 15.53632229  0.56193392]
    success=True, loglik=-2356.283, nit=14, nfev=90
  start 12/30: x0=[ 1.22903659  0.7004146  14.76863699  0.6972663 ]
    success=True, loglik=-2356.273, nit=18, nfev=115
  start 13/30: x0=[ 1.74302034  1.39598148 27.61313009  0.82416193]
    success=True, loglik=-2351.520, nit=15, nfev=135
  start 14/30: x0=[ 1.25270001  1.67003668 22.24565577  0.27841472]
    success=True, loglik=-2355.362, nit=9, nfev=70
  start 15/30: x0=[1.65793049 1.66900499 9.82381139 0.51014914]
    success=True, loglik=-2353.257, nit=7, nfev=65
  start 16/30: x0=[1.15004076 1.3478034  8.05170431 0.73141619]
    success=True, loglik=-2351.343, nit=23, nfev=135
  start 17/30: x0=[1.22154215 1.0396866  1.61686493 0.05027329]
    success=True, loglik=-2352.691, nit=16, nfev=110
  start 18/30: x0=[1.44769129 1.21689362 4.8774813  0.25953313]
    success=True, loglik=-2353.879, nit=9, nfev=65
  start 19/30: x0=[ 1.10222678  1.11751481 17.78514482  0.41738786]
    success=True, loglik=-2351.410, nit=13, nfev=85
  start 20/30: x0=[1.68457164 1.38568106 8.86321667 0.77425056]
    success=True, loglik=-2353.186, nit=9, nfev=70
  start 21/30: x0=[ 1.44964073  1.54779389 17.50336569  0.42681954]
    success=True, loglik=-2350.788, nit=8, nfev=75
  start 22/30: x0=[ 1.37730811  0.70877587 14.7173027   0.59990931]
    success=True, loglik=-2351.803, nit=13, nfev=85
  start 23/30: x0=[ 1.76227939  1.1793194  15.18647241  0.50277708]
    success=True, loglik=-2351.858, nit=11, nfev=90
  start 24/30: x0=[1.38601369 1.34274282 3.22609939 0.47419696]
    success=True, loglik=-2352.883, nit=8, nfev=55
  start 25/30: x0=[ 1.52710138  1.53078604 13.57911323  0.30160598]
    success=True, loglik=-2351.440, nit=10, nfev=65
  start 26/30: x0=[1.10412302 1.54513829 3.43418794 0.47568888]
    success=True, loglik=-2353.844, nit=7, nfev=50
  start 27/30: x0=[ 1.31305277  1.64121195 28.57370483  0.31655336]
    success=True, loglik=-2351.562, nit=12, nfev=110
  start 28/30: x0=[ 1.7284378   1.06792075 24.58882878  0.76292455]
    success=True, loglik=-2351.387, nit=11, nfev=95
  start 29/30: x0=[1.55869962 0.94395967 5.16502458 0.41466516]
    success=True, loglik=-2351.344, nit=23, nfev=150
  start 30/30: x0=[1.20607713 1.67817599 6.35885062 0.04817404]
    success=True, loglik=-2355.603, nit=7, nfev=55
  start 1/30: x0=[1.5        1.03547075 2.         0.1       ]
    success=True, loglik=-2137.621, nit=9, nfev=75
  start 2/30: x0=[1.5        1.03547075 5.         0.2       ]
    success=True, loglik=-2137.761, nit=7, nfev=60
  start 3/30: x0=[ 1.4         1.03547075 10.          0.1       ]
    success=True, loglik=-2139.623, nit=9, nfev=55
  start 4/30: x0=[ 1.6         1.03547075 10.          0.2       ]
    success=True, loglik=-2137.888, nit=9, nfev=75
  start 5/30: x0=[ 1.3         1.03547075 20.          0.1       ]
    success=True, loglik=-2136.380, nit=13, nfev=135
  start 6/30: x0=[1.5776463  0.67701254 7.54636434 0.19146578]
    success=True, loglik=-2140.162, nit=9, nfev=110
  start 7/30: x0=[ 1.22313413  1.46218256 27.79233594  0.27721419]
    success=True, loglik=-2138.058, nit=9, nfev=60
  start 8/30: x0=[ 1.67382819  1.54274031 15.97354911  0.24781708]
    success=True, loglik=-2137.552, nit=8, nfev=55
  start 9/30: x0=[ 1.67696912  0.84262775 22.5542511   0.60584439]
    success=True, loglik=-2136.328, nit=8, nfev=55
  start 10/30: x0=[ 1.74918508  0.8614166  24.2148037   0.50189348]
    success=True, loglik=-2136.285, nit=10, nfev=90
  start 11/30: x0=[ 1.26208894  0.79307119 15.53632229  0.56193392]
    success=True, loglik=-2137.058, nit=13, nfev=110
  start 12/30: x0=[ 1.22903659  0.6367057  14.76863699  0.6972663 ]
    success=True, loglik=-2138.482, nit=17, nfev=125
  start 13/30: x0=[ 1.74302034  1.26900462 27.61313009  0.82416193]
    success=True, loglik=-2136.328, nit=10, nfev=95
  start 14/30: x0=[ 1.25270001  1.51813208 22.24565577  0.27841472]
    success=True, loglik=-2137.723, nit=11, nfev=75
  start 15/30: x0=[1.65793049 1.51719423 9.82381139 0.51014914]
    success=True, loglik=-2138.612, nit=11, nfev=90
  start 16/30: x0=[1.15004076 1.22520877 8.05170431 0.73141619]
    success=True, loglik=-2140.547, nit=10, nfev=60
  start 17/30: x0=[1.22154215 0.94511791 1.61686493 0.05027329]
    success=True, loglik=-2137.148, nit=20, nfev=125
  start 18/30: x0=[1.44769129 1.10620639 4.8774813  0.25953313]
    success=True, loglik=-2139.417, nit=3, nfev=45
  start 19/30: x0=[ 1.10222678  1.01586696 17.78514482  0.41738786]
    success=True, loglik=-2136.745, nit=14, nfev=90
  start 20/30: x0=[1.68457164 1.25964111 8.86321667 0.77425056]
    success=True, loglik=-2139.287, nit=9, nfev=60
  start 21/30: x0=[ 1.44964073  1.40700835 17.50336569  0.42681954]
    success=True, loglik=-2136.803, nit=9, nfev=60
  start 22/30: x0=[ 1.37730811  0.64430644 14.7173027   0.59990931]
    success=True, loglik=-2138.478, nit=13, nfev=100
  start 23/30: x0=[ 1.76227939  1.07204988 15.18647241  0.50277708]
    success=True, loglik=-2136.484, nit=9, nfev=75
  start 24/30: x0=[1.38601369 1.22060849 3.22609939 0.47419696]
    success=True, loglik=-2137.749, nit=18, nfev=120
  start 25/30: x0=[ 1.52710138  1.39154751 13.57911323  0.30160598]
    success=True, loglik=-2136.961, nit=9, nfev=65
  start 26/30: x0=[1.10412302 1.4045943  3.43418794 0.47568888]
    success=True, loglik=-2137.749, nit=20, nfev=165
  start 27/30: x0=[ 1.31305277  1.49192921 28.57370483  0.31655336]
    success=True, loglik=-2138.108, nit=12, nfev=80
  start 28/30: x0=[ 1.7284378   0.97078391 24.58882878  0.76292455]
    success=True, loglik=-2136.283, nit=12, nfev=80
  start 29/30: x0=[1.55869962 0.85809819 5.16502458 0.41466516]
    success=True, loglik=-2142.245, nit=5, nfev=45
  start 30/30: x0=[1.20607713 1.52553105 6.35885062 0.04817404]
    success=True, loglik=-2138.170, nit=14, nfev=105
CPU times: total: 4min 32s
Wall time: 4min 46s

In [15]:
msm_fit_results_5 = {
    "NASDAQ": res_nasdaq_5,
    "S&P 500": res_sp500_5,
}

In [16]:
msm_fit_results_5

{'NASDAQ': MSMFitResult(asset='NASDAQ', k=5, params=MSMParams(m0=1.5099515751842003, sigma=1.5463133751015135, b=17.437947396085725, gamma_k=0.8622081702652361, gamma_1=2.1434827838340276e-05, k=5), log_likelihood=-2350.787756317032, success=True, message='CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*EPSMCH', nobs=1635, mean_return=0.06666781606711197),
 'S&P 500': MSMFitResult(asset='S&P 500', k=5, params=MSMParams(m0=1.5497260977124216, sigma=0.7878931452264746, b=24.541856781486622, gamma_k=0.9305471868008084, gamma_1=7.352064150700777e-06, k=5), log_likelihood=-2136.2833052449214, success=True, message='CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*EPSMCH', nobs=1635, mean_return=0.052717896639002546)}

In [ ]:
pit_msm = build_msm_pit_frame(
    returns=returns,
    fit_results=msm_fit_results_5,
)
#pit_msm.to_csv(PROCESSED_DATA_DIR / "pit_msm_5.csv")

In [15]:
pit_msm_5 = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_msm_5.csv",
    index_col="date",
    parse_dates=True,
)

## 5. GARCH

In [18]:
%%time

garch_results = fit_garch_marginals(
    returns=returns,
    mean="Constant",
    dist="normal",
    rescale=False,
)
garch_results

CPU times: total: 688 ms
Wall time: 1.25 s

{'NASDAQ': GARCHFitResult(asset='NASDAQ', model_result=                     Constant Mean - GARCH Model Results
 ==============================================================================
 Dep. Variable:                 NASDAQ   R-squared:                       0.000
 Mean Model:             Constant Mean   Adj. R-squared:                  0.000
 Vol Model:                      GARCH   Log-Likelihood:               -2368.82
 Distribution:                  Normal   AIC:                           4745.64
 Method:            Maximum Likelihood   BIC:                           4767.24
                                         No. Observations:                 1635
 Date:                Tue, May 19 2026   Df Residuals:                     1634
 Time:                        10:54:53   Df Model:                            1
                                 Mean Model
 ==========================================================================
                  coef    std err          t      P>|t|    95.0% Conf. Int.
 --------------------------------------------------------------------------
 mu             0.0948  2.317e-02      4.092  4.273e-05 [4.941e-02,  0.140]
                               Volatility Model
 ============================================================================
                  coef    std err          t      P>|t|      95.0% Conf. Int.
 ----------------------------------------------------------------------------
 omega          0.0440  1.172e-02      3.754  1.738e-04 [2.103e-02,6.696e-02]
 alpha[1]       0.1035  2.053e-02      5.041  4.634e-07   [6.325e-02,  0.144]
 beta[1]        0.8603  2.411e-02     35.687 6.186e-279     [  0.813,  0.908]
 ============================================================================

 Covariance estimator: robust
 ARCHModelResult, id: 0x1aa3509e810, mean=0.09482060564194653, omega=0.04399491405597585, alpha=0.10348133065549989, beta=0.8602576265609035, mean_se=0.023170922875067484, omega_se=0.011718469515069437, alpha_se=0.02052843888137634, beta_se=0.02410531535975635, log_likelihood=-2368.81897085924, aic=4745.63794171848, bic=4767.235534051805, nobs=1635, dist='normal'),
 'S&P 500': GARCHFitResult(asset='S&P 500', model_result=                     Constant Mean - GARCH Model Results
 ==============================================================================
 Dep. Variable:                S&P 500   R-squared:                       0.000
 Mean Model:             Constant Mean   Adj. R-squared:                  0.000
 Vol Model:                      GARCH   Log-Likelihood:               -2161.97
 Distribution:                  Normal   AIC:                           4331.94
 Method:            Maximum Likelihood   BIC:                           4353.54
                                         No. Observations:                 1635
 Date:                Tue, May 19 2026   Df Residuals:                     1634
 Time:                        10:54:53   Df Model:                            1
                                 Mean Model
 ==========================================================================
                  coef    std err          t      P>|t|    95.0% Conf. Int.
 --------------------------------------------------------------------------
 mu             0.0736  1.963e-02      3.752  1.758e-04 [3.516e-02,  0.112]
                               Volatility Model
 ============================================================================
                  coef    std err          t      P>|t|      95.0% Conf. Int.
 ----------------------------------------------------------------------------
 omega          0.0344  8.225e-03      4.179  2.932e-05 [1.825e-02,5.049e-02]
 alpha[1]       0.1252  2.287e-02      5.475  4.379e-08   [8.040e-02,  0.170]
 beta[1]        0.8410  2.335e-02     36.014 5.107e-284     [  0.795,  0.887]
 ============================================================================

 Covariance estimator: robust
 ARCHModelResult, id: 0x1aa35128690, mean=0.07362577957868395, omega=0.0343682966162745, alpha=0.12523432288724942, beta=0.8410426364065152, mean_se=0.019625664726554318, omega_se=0.008224666708628434, alpha_se=0.022874476922393586, beta_se=0.023353412662621677, log_likelihood=-2161.9705779699048, aic=4331.9411559398095, bic=4353.538748273135, nobs=1635, dist='normal')}

In [19]:
garch_table = garch_results_table(garch_results)
garch_table

,asset,mean,mean_se,omega,omega_se,alpha,alpha_se,beta,beta_se,log_likelihood,...,Arch(5),Arch(5) p-value,Arch(10),Arch(10) p-value,Q(2),Q(2) p-value,Q(4),Q(4) p-value,Q(8),Q(8) p-value
0,NASDAQ,0.094821,0.023171,0.043995,0.011718,0.103481,0.020528,0.860258,0.024105,-2368.818971,...,8.185071,0.146327,10.492696,0.398381,0.037705,0.981324,3.775267,0.437274,4.959775,0.761867
1,S&P 500,0.073626,0.019626,0.034368,0.008225,0.125234,0.022874,0.841043,0.023353,-2161.970578,...,16.262379,0.006134,18.804659,0.042815,1.037366,0.595304,2.639331,0.619872,7.459761,0.487934

In [ ]:
#garch_table.to_csv(REPORTS_DIR / "tables" / "table_3_garch_estimates_raw.csv", index=False)

In [14]:
garch_table = pd.read_csv(REPORTS_DIR / "tables" / "table_3_garch_estimates_raw.csv")

In [21]:
table_3_garch = format_garch_table_3(garch_table)
table_3_garch

,omega,alpha,beta,Arch(1),Arch(5),Arch(10),Q(2),Q(4),Q(8)
asset,,,,,,,,,
NASDAQ,0.044 [0.012],0.103 [0.021],0.860 [0.024],1.740 (0.187),8.185 (0.146),10.493 (0.398),0.038 (0.981),3.775 (0.437),4.960 (0.762)
S&P 500,0.034 [0.008],0.125 [0.023],0.841 [0.023],4.222 (0.040),16.262 (0.006),18.805 (0.043),1.037 (0.595),2.639 (0.620),7.460 (0.488)

In [ ]:
#table_3_garch.to_csv(REPORTS_DIR / "tables" / "table_3_garch_estimates_formatted.csv")

In [16]:
table_3_garch = pd.read_csv(REPORTS_DIR / "tables" / "table_3_garch_estimates_formatted.csv")

### Conditional Vol

In [43]:
garch_volatility = build_garch_volatility_frame(garch_results)
garch_volatility

              NASDAQ   S&P 500
date
2009-04-16  1.771182  1.768811
2009-04-17  1.848471  1.713396
2009-04-20  1.727358  1.589261
2009-04-21  2.075341  2.152921
2009-04-22  2.050428  2.109120
...              ...       ...
2015-10-06  1.413941  1.298467
2015-10-07  1.351911  1.214854
2015-10-08  1.297253  1.158351
2015-10-09  1.225525  1.115296
2015-10-12  1.160255  1.039485

[1635 rows x 2 columns]

In [ ]:
#garch_volatility.to_csv(PROCESSED_DATA_DIR / "garch_conditional_volatility.csv")

In [99]:
garch_volatility = pd.read_csv(PROCESSED_DATA_DIR / "garch_conditional_volatility.csv", index_col="date", parse_dates=True)

### PIT GARCH

In [23]:
pit_garch = build_garch_pit_frame(garch_results)
pit_garch

              NASDAQ   S&P 500
date
2009-04-16  0.925217  0.796761
2009-04-17  0.513486  0.597291
2009-04-20  0.009543  0.002571
2009-04-21  0.843870  0.827054
2009-04-22  0.508400  0.344385
...              ...       ...
2015-10-06  0.289311  0.369362
2015-10-07  0.723561  0.725147
2015-10-08  0.595709  0.756282
2015-10-09  0.600928  0.499592
2015-10-12  0.525485  0.520654

[1635 rows x 2 columns]

In [24]:
pit_garch.describe()

            NASDAQ      S&P 500
count  1635.000000  1635.000000
mean      0.499149     0.498485
std       0.275217     0.273879
min       0.000041     0.000022
25%       0.301117     0.291500
50%       0.506885     0.499895
75%       0.720656     0.714563
max       0.997744     0.999363

In [25]:
pit_garch.isna().sum()

NASDAQ     0
S&P 500    0
dtype: int64

In [ ]:
#pit_garch.to_csv(PROCESSED_DATA_DIR / "pit_garch.csv")

In [85]:
pit_garch = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_garch.csv",
    index_col="date",
    parse_dates=True,
)

## 6. Copulas

### MSM specifications used below

We keep three MSM specifications:

1. `paper_like_table2`: NASDAQ \(k=3\), S&P 500 \(k=4\), close to the model selection in Table 2.
2. `empirical_best`: NASDAQ \(k=3\), S&P 500 \(k=3\), selected from our likelihood table.
3. `paper_like_var`: NASDAQ \(k=5\), S&P 500 \(k=5\), because Table 4 and the VaR section of Segnon and Trede fix the MSM volatility components at \(k=5\).

The main VaR backtest will start with the `paper_like_var` specification.

In [19]:
pit_msm = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_msm_5.csv",
    index_col="date",
    parse_dates=True,
)
pit_msm_emp = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_msm_emp.csv",
    index_col="date",
    parse_dates=True,
)
pit_garch = pd.read_csv(
    PROCESSED_DATA_DIR / "pit_garch.csv",
    index_col="date",
    parse_dates=True,
)

### paperilike : k=5

In [28]:
%%time

copula_results = fit_copula_grid(
    pit_by_model={
        "MSM": pit_msm,
        "GARCH": pit_garch,
    }
)

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:240: RuntimeWarning: overflow encountered in power

CPU times: total: 9.14 s
Wall time: 9.62 s

In [29]:
copula_table = copula_results_table(copula_results)
copula_table

,margin_model,copula,log_likelihood,aic,bic,nobs,success,message,rho,nu,theta,tau_u,tau_l
0,MSM,gaussian,1790.237713,-3578.475426,-3573.076028,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,0.945020,NaN,NaN,NaN,NaN
1,MSM,student,1816.377223,-3628.754447,-3617.955651,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,0.944521,5.628161,NaN,NaN,NaN
2,MSM,plackett,1681.462603,-3360.925206,-3355.525808,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,75.222744,NaN,NaN
3,MSM,clayton,1471.764013,-2941.528025,-2936.128627,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.612738,NaN,NaN
4,MSM,rotated_clayton,1505.239404,-3008.478808,-3003.079410,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.888786,NaN,NaN
5,MSM,sjc,1805.082698,-3606.165397,-3595.366601,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,NaN,0.848531,0.820338
6,MSM,frank,1532.348929,-3062.697858,-3057.298460,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,20.000000,NaN,NaN
7,MSM,gumbel,1758.985979,-3515.971958,-3510.572560,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.480543,NaN,NaN
8,MSM,rotated_gumbel,1728.424141,-3454.848283,-3449.448885,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.389183,NaN,NaN
9,GARCH,gaussian,1841.477032,-3680.954064,-3675.554666,1635,True,CONVERGENCE: NORM OF PROJECTED GRADIENT <= PGTOL,0.945868,NaN,NaN,NaN,NaN
10,GARCH,student,1846.797074,-3689.594149,-3678.795353,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,0.946422,17.532720,NaN,NaN,NaN
11,GARCH,plackett,1755.369069,-3508.738138,-3503.338740,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,80.697578,NaN,NaN
12,GARCH,clayton,1387.640209,-2773.280419,-2767.881021,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.212784,NaN,NaN
13,GARCH,rotated_clayton,1443.324315,-2884.648630,-2879.249232,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.997749,NaN,NaN
14,GARCH,sjc,1687.393318,-3370.786637,-3359.987841,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,NaN,0.842021,0.753968
15,GARCH,frank,1677.308063,-3352.616126,-3347.216728,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,20.000000,NaN,NaN
16,GARCH,gumbel,1779.136035,-3556.272071,-3550.872673,1635,True,CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*...,NaN,NaN,4.527290,NaN,NaN
17,GARCH,rotated_gumbel,1701.339668,-3400.679335,-3395.279937,1635,True,CONVERGENCE: NORM OF PROJECTED GRADIENT <= PGTOL,NaN,NaN,4.206483,NaN,NaN

In [30]:
table_4 = format_copula_table_4(copula_table)
table_4

,margin_model,copula,parameters,Log(L),AIC,BIC
0,MSM,gaussian,rho=0.945,1790.238,-3578.475,-3573.076
1,MSM,student,"rho=0.945, nu=5.628",1816.377,-3628.754,-3617.956
2,MSM,plackett,theta=75.223,1681.463,-3360.925,-3355.526
3,MSM,clayton,theta=4.613,1471.764,-2941.528,-2936.129
4,MSM,rotated_clayton,theta=4.889,1505.239,-3008.479,-3003.079
5,MSM,sjc,"tau_u=0.849, tau_l=0.820",1805.083,-3606.165,-3595.367
6,MSM,frank,theta=20.000,1532.349,-3062.698,-3057.298
7,MSM,gumbel,theta=4.481,1758.986,-3515.972,-3510.573
8,MSM,rotated_gumbel,theta=4.389,1728.424,-3454.848,-3449.449
9,GARCH,gaussian,rho=0.946,1841.477,-3680.954,-3675.555
10,GARCH,student,"rho=0.946, nu=17.533",1846.797,-3689.594,-3678.795
11,GARCH,plackett,theta=80.698,1755.369,-3508.738,-3503.339
12,GARCH,clayton,theta=4.213,1387.640,-2773.280,-2767.881
13,GARCH,rotated_clayton,theta=4.998,1443.324,-2884.649,-2879.249
14,GARCH,sjc,"tau_u=0.842, tau_l=0.754",1687.393,-3370.787,-3359.988
15,GARCH,frank,theta=20.000,1677.308,-3352.616,-3347.217
16,GARCH,gumbel,theta=4.527,1779.136,-3556.272,-3550.873
17,GARCH,rotated_gumbel,theta=4.206,1701.340,-3400.679,-3395.280

In [ ]:
# copula_table.to_csv(
#     REPORTS_DIR / "tables" / "table_4_copula_estimates_raw.csv",
#     index=False,
# )

In [ ]:
# table_4.to_csv(
#     REPORTS_DIR / "tables" / "table_4_copula_estimates_formatted.csv",
#     index=False,
# )

In [33]:
best_loglik = (
    copula_table
    .loc[copula_table.groupby("margin_model")["log_likelihood"].idxmax()]
    .sort_values("margin_model")
)
best_aic = (
    copula_table
    .loc[copula_table.groupby("margin_model")["aic"].idxmin()]
    .sort_values("margin_model")
)
best_bic = (
    copula_table
    .loc[copula_table.groupby("margin_model")["bic"].idxmin()]
    .sort_values("margin_model")
)

best_summary = pd.concat(
    {
        "Max Log(L)": best_loglik,
        "Min AIC": best_aic,
        "Min BIC": best_bic,
    },
    names=["criterion"]
).reset_index(level=0)
best_summary[
    ["criterion", "margin_model", "copula", "log_likelihood", "aic", "bic", "rho", "nu", "theta"]
]

,criterion,margin_model,copula,log_likelihood,aic,bic,rho,nu,theta
10,Max Log(L),GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Max Log(L),MSM,student,1816.377223,-3628.754447,-3617.955651,0.944521,5.628161,NaN
10,Min AIC,GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Min AIC,MSM,student,1816.377223,-3628.754447,-3617.955651,0.944521,5.628161,NaN
10,Min BIC,GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Min BIC,MSM,student,1816.377223,-3628.754447,-3617.955651,0.944521,5.628161,NaN

### empirical_best: k=3

In [76]:
%%time

copula_results_emp = fit_copula_grid(
    pit_by_model={
        "MSM": pit_msm_emp,
        "GARCH": pit_garch,
    }
)

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:182: RuntimeWarning: divide by zero encountered in divide
  density = numerator / denominator

CPU times: total: 5.36 s
Wall time: 5.49 s

In [77]:
copula_table_emp = copula_results_table(copula_results_emp)
table_4_emp = format_copula_table_4(copula_table_emp)
table_4_emp

,margin_model,copula,parameters,Log(L),AIC,BIC
0,MSM,gaussian,rho=0.946,1799.563,-3597.125,-3591.726
1,MSM,student,"rho=0.945, nu=5.576",1825.919,-3647.837,-3637.038
2,MSM,plackett,theta=75.673,1686.451,-3370.902,-3365.503
3,MSM,clayton,theta=4.657,1485.549,-2969.098,-2963.699
4,MSM,rotated_clayton,theta=4.903,1510.657,-3019.315,-3013.915
5,MSM,frank,theta=20.000,1537.477,-3072.953,-3067.554
6,MSM,gumbel,theta=4.494,1766.015,-3530.029,-3524.630
7,MSM,rotated_gumbel,theta=4.415,1740.900,-3479.799,-3474.400
8,GARCH,gaussian,rho=0.946,1841.477,-3680.954,-3675.555
9,GARCH,student,"rho=0.946, nu=17.533",1846.797,-3689.594,-3678.795
10,GARCH,plackett,theta=80.698,1755.369,-3508.738,-3503.339
11,GARCH,clayton,theta=4.213,1387.640,-2773.280,-2767.881
12,GARCH,rotated_clayton,theta=4.998,1443.324,-2884.649,-2879.249
13,GARCH,frank,theta=20.000,1677.308,-3352.616,-3347.217
14,GARCH,gumbel,theta=4.527,1779.136,-3556.272,-3550.873
15,GARCH,rotated_gumbel,theta=4.206,1701.340,-3400.679,-3395.280

In [ ]:
# copula_table_emp.to_csv(
#     REPORTS_DIR / "tables" / "table_4_copula_estimates_raw_emp.csv",
#     index=False,
# )

In [ ]:
# table_4_emp.to_csv(
#     REPORTS_DIR / "tables" / "table_4_copula_estimates_formatted_emp.csv",
#     index=False,
# )

In [81]:
best_loglik_emp = (
    copula_table_emp
    .loc[copula_table_emp.groupby("margin_model")["log_likelihood"].idxmax()]
    .sort_values("margin_model")
)
best_aic_emp = (
    copula_table_emp
    .loc[copula_table_emp.groupby("margin_model")["aic"].idxmin()]
    .sort_values("margin_model")
)
best_bic_emp = (
    copula_table_emp
    .loc[copula_table_emp.groupby("margin_model")["bic"].idxmin()]
    .sort_values("margin_model")
)

best_summary = pd.concat(
    {
        "Max Log(L)": best_loglik_emp,
        "Min AIC": best_aic_emp,
        "Min BIC": best_bic_emp,
    },
    names=["criterion"]
).reset_index(level=0)
best_summary[
    ["criterion", "margin_model", "copula", "log_likelihood", "aic", "bic", "rho", "nu", "theta"]
]

,criterion,margin_model,copula,log_likelihood,aic,bic,rho,nu,theta
9,Max Log(L),GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Max Log(L),MSM,student,1825.918610,-3647.837221,-3637.038425,0.944905,5.575925,NaN
9,Min AIC,GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Min AIC,MSM,student,1825.918610,-3647.837221,-3637.038425,0.944905,5.575925,NaN
9,Min BIC,GARCH,student,1846.797074,-3689.594149,-3678.795353,0.946422,17.532720,NaN
1,Min BIC,MSM,student,1825.918610,-3647.837221,-3637.038425,0.944905,5.575925,NaN

## 7. Portfolio VaR

Reproduction of VaR - paper methodolodgy:
- fixed estimation window of 1135 observations ;
- 500 out-of-sample predictions ;
- portfolio equaly weighted by `PI` ;
- one-day ahead VaRs (5% and 1%)

Convention used: 

Var as a quantile :
$$
P(r_{p,t} \leq VaR_t(\alpha) \mid \Omega_{t-1}) = \alpha
$$

Violation happens when :
$$
r_{p,t} < VaR_t(\alpha)
$$

### 7.1 Parameters

In [2]:
PI = 0.5
WEIGHTS = np.array([PI, 1.0 - PI])
N_OOS = 500
WINDOW_SIZE = 1135

ALPHA_5 = 0.05
ALPHA_1 = 0.01

VAR_OUTPUT_DIR = TABLES_DIR / "var_forecasts"
VAR_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WEIGHTS, WINDOW_SIZE, N_OOS

(array([0.5, 0.5]), 1135, 500)

In [3]:
returns = pd.read_csv(
    PROCESSED_DATA_DIR / "returns_nasdaq_sp500.csv",
    index_col="date",
    parse_dates=True,
)
returns

              NASDAQ   S&P 500
date
2009-04-16  2.647210  1.541931
2009-04-17  0.157320  0.495705
2009-04-20 -3.953850 -4.373221
2009-04-21  2.191930  2.102938
2009-04-22  0.137996 -0.771132
...              ...       ...
2015-10-06 -0.690479 -0.359469
2015-10-07  0.897118  0.800352
2015-10-08  0.409087  0.877978
2015-10-09  0.408250  0.072485
2015-10-12  0.168990  0.127466

[1635 rows x 2 columns]

### 7.2 Portfolio with out-of-sample returns

In [4]:
returns_var = prepare_bivariate_returns(
    returns,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
)

portfolio_ret = var_v2_portfolio_returns(
    returns_var,
    weights=WEIGHTS,
)

oos_index = returns_var.index[WINDOW_SIZE:WINDOW_SIZE + N_OOS]
portfolio_ret_oos = portfolio_ret.loc[oos_index]

print("returns_var shape:", returns_var.shape)
print("OOS length:", len(portfolio_ret_oos))
print("OOS start:", portfolio_ret_oos.index.min())
print("OOS end:", portfolio_ret_oos.index.max())

assert len(portfolio_ret_oos) == N_OOS

returns_var shape: (1635, 2)
OOS length: 500
OOS start: 2013-10-17 00:00:00
OOS end: 2015-10-12 00:00:00

### 7.3 utils

In [5]:
def save_var(series: pd.Series, filename: str) -> Path:
    """Save one VaR forecast series."""
    path = VAR_OUTPUT_DIR / filename
    series.to_frame(name=series.name or "VaR").to_csv(path)
    print(f"Saved: {path}")
    return path


def load_var(filename: str, column_name: str | None = None) -> pd.Series:
    """Load one saved VaR forecast series."""
    path = VAR_OUTPUT_DIR / filename
    frame = pd.read_csv(path, index_col=0, parse_dates=True)
    series = frame.iloc[:, 0]
    if column_name is not None:
        series.name = column_name
    return series


def concat_var_series(series_by_name: dict[str, pd.Series]) -> pd.DataFrame:
    """Concatenate VaR forecasts and align on common dates."""
    frame = pd.concat(
        {name: series for name, series in series_by_name.items()},
        axis=1,
    ).dropna(how="any")
    
    assert len(frame) == N_OOS, f"Expected {N_OOS} observations, got {len(frame)}"
    return frame


def backtest_var_panel(var_panel: pd.DataFrame, alpha: float) -> pd.DataFrame:
    """Compute violation frequency and Christoffersen LR tests for a VaR panel."""
    rows = []

    for model in var_panel.columns:
        hits = var_v2_var_exceedances(portfolio_ret_oos, var_panel[model])
        lr = christoffersen_lr_test(hits, alpha=alpha)

        rows.append(
            {
                "model": model,
                "alpha": alpha,
                "violations": int(hits.sum()),
                "EFV": hits.mean(),
                "LR_uc": lr["uc_stat"],
                "p_uc": lr["uc_pvalue"],
                "LR_ind": lr["ind_stat"],
                "p_ind": lr["ind_pvalue"],
                "LR_cc": lr["cc_stat"],
                "p_cc": lr["cc_pvalue"],
            }
        )

    return pd.DataFrame(rows).set_index("model")

### 7.4 VaR 5% — benchmark models

Fast models:
- Historical Simulation ;
- Variance-Covariance ;
- RiskMetrics ;
- CCC-GARCH.

In [7]:
# Historical Simulation VaR 5%

var_hist_5 = forecast_historical_var_rolling(
    returns=returns_var,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
)

save_var(var_hist_5.rename("Historical"), "var_hist_5.csv")
var_hist_5.head()

Saved: C:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\reports\tables\var_forecasts\var_hist_5.csv

2013-10-17   -1.894145
2013-10-18   -1.894145
2013-10-21   -1.894145
2013-10-22   -1.885447
2013-10-23   -1.885447
Name: HS_VaR_0.05, dtype: float64

In [8]:
# Variance-Covariance VaR 5%

var_vc_5 = forecast_variance_covariance_var_rolling(
    returns=returns_var,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=True,
)

save_var(var_vc_5.rename("Variance-Covariance"), "var_vc_5.csv")
var_vc_5.head()

Saved: C:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\reports\tables\var_forecasts\var_vc_5.csv

2013-10-17   -1.828738
2013-10-18   -1.827642
2013-10-21   -1.827548
2013-10-22   -1.812499
2013-10-23   -1.811373
Name: VarCov_VaR_0.05, dtype: float64

In [9]:
# RiskMetrics VaR 5%

var_rm_5 = forecast_riskmetrics_var_rolling(
    returns=returns_var,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    lambda_=0.94,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=False,
)

save_var(var_rm_5.rename("RiskMetrics"), "var_rm_5.csv")
var_rm_5.head()

Saved: C:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\reports\tables\var_forecasts\var_rm_5.csv

2013-10-17   -1.910840
2013-10-18   -1.870711
2013-10-21   -1.856529
2013-10-22   -1.800248
2013-10-23   -1.753104
Name: RiskMetrics_VaR_0.05, dtype: float64

In [10]:
# CCC-GARCH VaR 5%

var_ccc_5 = forecast_ccc_garch_var_rolling(
    returns=returns_var,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=True,
    verbose=True,
)

save_var(var_ccc_5.rename("CCC-GARCH"), "var_ccc_5.csv")
var_ccc_5.head()

CCC-GARCH alpha=0.05: 25/500, VaR=-1.1924
CCC-GARCH alpha=0.05: 50/500, VaR=-1.1154
CCC-GARCH alpha=0.05: 75/500, VaR=-2.0139
CCC-GARCH alpha=0.05: 100/500, VaR=-1.1234
CCC-GARCH alpha=0.05: 125/500, VaR=-1.8614
CCC-GARCH alpha=0.05: 150/500, VaR=-1.2264
CCC-GARCH alpha=0.05: 175/500, VaR=-0.8985
CCC-GARCH alpha=0.05: 200/500, VaR=-1.4178
CCC-GARCH alpha=0.05: 225/500, VaR=-0.8564
CCC-GARCH alpha=0.05: 250/500, VaR=-2.1387
CCC-GARCH alpha=0.05: 275/500, VaR=-0.9747
CCC-GARCH alpha=0.05: 300/500, VaR=-1.6548
CCC-GARCH alpha=0.05: 325/500, VaR=-1.6683
CCC-GARCH alpha=0.05: 350/500, VaR=-1.1502
CCC-GARCH alpha=0.05: 375/500, VaR=-1.0054
CCC-GARCH alpha=0.05: 400/500, VaR=-1.0938
CCC-GARCH alpha=0.05: 425/500, VaR=-1.1255
CCC-GARCH alpha=0.05: 450/500, VaR=-1.2423
CCC-GARCH alpha=0.05: 475/500, VaR=-2.9218
CCC-GARCH alpha=0.05: 500/500, VaR=-1.5973
Saved: C:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\reports\tables\var_forecasts\var_ccc_5.csv

2013-10-17   -1.574050
2013-10-18   -1.516937
2013-10-21   -1.509214
2013-10-22   -1.432491
2013-10-23   -1.374955
Name: CCC_GARCH_VaR_0.05, dtype: float64

#### Copula-GARCH

In [ ]:
# Copula-GARCH Student VaR 5%

var_garch_student_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula="student",
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(var_garch_student_5.rename("Copula-GARCH Student"), "var_garch_student_5.csv")
var_garch_student_5.head()

In [ ]:
COPULA_TO_RUN = "gaussian"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [6]:
COPULA_TO_RUN = "sjc"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 25/500, VaR=-1.1848

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 50/500, VaR=-1.1092

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 75/500, VaR=-2.0026

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 100/500, VaR=-1.1173

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 125/500, VaR=-1.8511

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 150/500, VaR=-1.2210

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 175/500, VaR=-0.8939

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 200/500, VaR=-1.4110

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 225/500, VaR=-0.8520

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 250/500, VaR=-2.1289

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 275/500, VaR=-0.9703

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 300/500, VaR=-1.6462

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 325/500, VaR=-1.6569

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 350/500, VaR=-1.1427

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 375/500, VaR=-0.9981

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 400/500, VaR=-1.0852

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 425/500, VaR=-1.1170

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 450/500, VaR=-1.2350

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 475/500, VaR=-2.8978

c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0
c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\src\copulas.py:241: RuntimeWarning: overflow encountered in power
  s = a ** (-gamma) + b ** (-gamma) - 1.0

GARCH-sjc alpha=0.05: 500/500, VaR=-1.5862
Saved: C:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Gestion Quantitative\Réplication 2\Forecasting_market_risk-Copula_MSM_Approach\reports\tables\var_forecasts\var_garch_sjc_5.csv

2013-10-17   -1.564764
2013-10-18   -1.507716
2013-10-21   -1.500353
2013-10-22   -1.423910
2013-10-23   -1.366841
Name: CopulaGARCH_sjc_VaR_0.05, dtype: float64

In [ ]:
COPULA_TO_RUN = "clayton"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [ ]:
COPULA_TO_RUN = "rotated_clayton"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [ ]:
COPULA_TO_RUN = "sjc"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [ ]:
COPULA_TO_RUN = "frank"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [ ]:
COPULA_TO_RUN = "gumbel"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

In [ ]:
COPULA_TO_RUN = "rotated_gumbel"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_5 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_5.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_5.csv",
)

var_garch_extra_5.head()

### 7.5 VaR 5% - Copula-MSM

In [11]:
# Copula-MSM Student VaR 5%

var_msm_student_5 = forecast_msm_copula_var_rolling(
    returns=returns_var,
    copula="student",
    alpha=ALPHA_5,
    weights=WEIGHTS,
    k=5,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    n_starts=10,
    seed=123,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(var_msm_student_5.rename("Copula-MSM Student"), "var_msm_student_5.csv")
var_msm_student_5.head()

MSM-student alpha=0.05: 10/500, VaR=-1.1386
MSM-student alpha=0.05: 20/500, VaR=-1.2786
MSM-student alpha=0.05: 30/500, VaR=-1.1103
MSM-student alpha=0.05: 40/500, VaR=-1.2532
MSM-student alpha=0.05: 50/500, VaR=-1.1323
MSM-student alpha=0.05: 60/500, VaR=-1.0251

KeyboardInterrupt:

In [ ]:
COPULA_TO_RUN = "plackett"  # options: plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_msm_extra_5 = forecast_msm_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_5,
    weights=WEIGHTS,
    k=5,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    n_starts=10,
    seed=123,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_msm_extra_5.rename(f"Copula-MSM {COPULA_TO_RUN}"),
    f"var_msm_{COPULA_TO_RUN}_5.csv",
)

var_msm_extra_5.head()

### 7.6 VaR 5% - concat

In [7]:
var_series_fig = {
    "Historical": load_var("var_hist_5.csv"),
    "Variance-Covariance": load_var("var_vc_5.csv"),
    "RiskMetrics": load_var("var_rm_5.csv"),
    "CCC-GARCH": load_var("var_ccc_5.csv"),
    "Copula-GARCH Student": load_var("var_garch_student_5.csv"),
    "Copula-MSM Student": load_var("var_msm_student_5.csv"),
}

var_panel_fig = concat_var_series(var_series_fig)

var_panel_fig.to_csv(VAR_OUTPUT_DIR / "var_panel_fig.csv")

In [27]:
var_series_all = {
    "Historical": load_var("var_hist_5.csv"),
    "Variance-Covariance": load_var("var_vc_5.csv"),
    "RiskMetrics": load_var("var_rm_5.csv"),
    "CCC-GARCH": load_var("var_ccc_5.csv"),
    "Copula-GARCH Student": load_var("var_garch_student_5.csv"),
    "Copula-GARCH Gaussian": load_var("var_garch_gaussian_5.csv"),
    "Copula-GARCH Plackett": load_var("var_garch_plackett_5.csv"),
    "Copula-GARCH Clayton": load_var("var_garch_clayton_5.csv"),
    "Copula-GARCH Rotated Clayton": load_var("var_garch_rotated_clayton_5.csv"),
    "Copula-GARCH SJC": load_var("var_garch_sjc_5.csv"),
    "Copula-GARCH Frank": load_var("var_garch_frank_5.csv"),
    "Copula-GARCH Gumbel": load_var("var_garch_gumbel_5.csv"),
    "Copula-GARCH Rotated Gumbel": load_var("var_garch_rotated_gumbel_5.csv"),
    "Copula-MSM Student": load_var("var_msm_student_5.csv"),
    "Copula-MSM Gaussian": load_var("var_msm_gaussian_5.csv"),
    #"Copula-MSM Plackett": load_var("var_msm_plackett_5.csv"),
    #"Copula-MSM Clayton": load_var("var_msm_clayton_5.csv"),
    #"Copula-MSM Rotated Clayton": load_var("var_msm_rotated_clayton_5.csv"),
    #"Copula-MSM SJC": load_var("var_msm_sjc_5.csv"),
    #"Copula-MSM Frank": load_var("var_msm_frank_5.csv"),
    #"Copula-MSM Gumbel": load_var("var_msm_gumbel_5.csv"),
    #"Copula-MSM Rotated Gumbel": load_var("var_msm_rotated_gumbel_5.csv"),
}

var_panel_all = concat_var_series(var_series_all)

var_panel_all.to_csv(VAR_OUTPUT_DIR / "var_panel_all.csv")
var_panel_all.head()

,Historical,Variance-Covariance,RiskMetrics,CCC-GARCH,Copula-GARCH Student,Copula-GARCH Gaussian,Copula-GARCH Plackett,Copula-GARCH Clayton,Copula-GARCH Rotated Clayton,Copula-GARCH SJC,Copula-GARCH Frank,Copula-GARCH Gumbel,Copula-GARCH Rotated Gumbel,Copula-MSM Student,Copula-MSM Gaussian
2013-10-17,-1.894145,-1.828738,-1.910840,-1.574050,-1.574052,-1.574028,-1.562749,-1.584488,-1.470044,-1.564764,-1.571929,-1.554903,-1.581432,-1.644574,-1.645104
2013-10-18,-1.894145,-1.827642,-1.870711,-1.516937,-1.516933,-1.516911,-1.506014,-1.527016,-1.416833,-1.507716,-1.514875,-1.498525,-1.524069,-1.594554,-1.595078
2013-10-21,-1.894145,-1.827548,-1.856529,-1.509214,-1.509214,-1.509196,-1.498351,-1.519248,-1.409575,-1.500353,-1.505908,-1.490878,-1.516312,-1.626070,-1.626556
2013-10-22,-1.885447,-1.812499,-1.800248,-1.432491,-1.432539,-1.432501,-1.422304,-1.442232,-1.337011,-1.423910,-1.440224,-1.414939,-1.439409,-1.512771,-1.515012
2013-10-23,-1.885447,-1.811373,-1.753104,-1.374955,-1.375004,-1.374967,-1.365100,-1.384396,-1.282619,-1.366841,-1.376855,-1.357950,-1.381657,-1.436967,-1.438793

### 7.7 VaR 5% - Graph

In [8]:
fig3 = plot_var_forecasts(
    portfolio_returns=portfolio_ret_oos.rename("Portfolio returns"),
    var_forecasts=var_panel_fig,
    output_path=REPORTS_DIR / "figures" / "figure_3_var_5pct.html",
    title="Figure 3 — VaR forecasts at the 5% confidence level",
    positive_loss_var=False,
)

fig3.show()

In [9]:
fig3.write_image(
    REPORTS_DIR / "figures" / "figure_3_var_5pct.png",
    scale=2,
)

### 7.8 VaR 1% - benchmark models

In [ ]:
var_hist_1 = forecast_historical_var_rolling(
    returns=returns_var,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
)
save_var(var_hist_1.rename("Historical"), "var_hist_1.csv")

var_vc_1 = forecast_variance_covariance_var_rolling(
    returns=returns_var,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=True,
)
save_var(var_vc_1.rename("Variance-Covariance"), "var_vc_1.csv")

var_rm_1 = forecast_riskmetrics_var_rolling(
    returns=returns_var,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    lambda_=0.94,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=False,
)
save_var(var_rm_1.rename("RiskMetrics"), "var_rm_1.csv")

var_ccc_1 = forecast_ccc_garch_var_rolling(
    returns=returns_var,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    include_mean=True,
    verbose=True,
)
save_var(var_ccc_1.rename("CCC-GARCH"), "var_ccc_1.csv")

#### Copula-GARCH

In [ ]:
var_garch_student_1 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula="student",
    alpha=ALPHA_1,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)
save_var(var_garch_student_1.rename("Copula-GARCH Student"), "var_garch_student_1.csv")
var_garch_student_1.head()

In [ ]:
COPULA_TO_RUN = "gaussian"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_garch_extra_1 = forecast_garch_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_garch_extra_1.rename(f"Copula-GARCH {COPULA_TO_RUN}"),
    f"var_garch_{COPULA_TO_RUN}_1.csv",
)

var_garch_extra_1.head()

### 7.9 VaR 1% - Copula-MSM

In [ ]:
var_msm_student_1 = forecast_msm_copula_var_rolling(
    returns=returns_var,
    copula="student",
    alpha=ALPHA_1,
    weights=WEIGHTS,
    k=5,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    n_starts=10,
    seed=123,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(var_msm_student_1.rename("Copula-MSM Student"), "var_msm_student_1.csv")
var_msm_student_1.head()

In [6]:
COPULA_TO_RUN = "gaussian"  # options: gaussian, plackett, clayton, rotated_clayton, sjc, frank, gumbel, rotated_gumbel

var_msm_extra_1 = forecast_msm_copula_var_rolling(
    returns=returns_var,
    copula=COPULA_TO_RUN,
    alpha=ALPHA_1,
    weights=WEIGHTS,
    k=5,
    n_insample=WINDOW_SIZE,
    n_oos=N_OOS,
    n_starts=10,
    seed=123,
    integration_nodes=501,
    root_tol=1e-4,
    verbose=True,
)

save_var(
    var_msm_extra_1.rename(f"Copula-MSM {COPULA_TO_RUN}"),
    f"var_msm_{COPULA_TO_RUN}_1.csv",
)

var_msm_extra_1.head()

MSM-gaussian alpha=0.01: 10/500, VaR=-1.9559, x1=[ 1.5245  1.6205 22.7343  0.9332], x2=[ 1.5464  1.5025 24.5116  0.9309]

KeyboardInterrupt:

### 7.10 VaR 1% - concat

In [10]:
var_series_fig_1 = {
    "Historical": load_var("var_hist_1.csv"),
    "Variance-Covariance": load_var("var_vc_1.csv"),
    "RiskMetrics": load_var("var_rm_1.csv"),
    "CCC-GARCH": load_var("var_ccc_1.csv"),
    "Copula-GARCH Student": load_var("var_garch_student_1.csv"),
    "Copula-MSM Student": load_var("var_msm_student_1.csv"),
}

var_panel_fig_1 = concat_var_series(var_series_fig_1)

var_panel_fig_1.to_csv(VAR_OUTPUT_DIR / "var_panel_fig_1.csv")

In [28]:
var_series_all_1 = {
    "Historical": load_var("var_hist_1.csv"),
    "Variance-Covariance": load_var("var_vc_1.csv"),
    "RiskMetrics": load_var("var_rm_1.csv"),
    "CCC-GARCH": load_var("var_ccc_1.csv"),
    "Copula-GARCH Student": load_var("var_garch_student_1.csv"),
    "Copula-GARCH Gaussian": load_var("var_garch_gaussian_1.csv"),
    "Copula-GARCH Plackett": load_var("var_garch_plackett_1.csv"),
    "Copula-GARCH Clayton": load_var("var_garch_clayton_1.csv"),
    "Copula-GARCH Rotated Clayton": load_var("var_garch_rotated_clayton_1.csv"),
    "Copula-GARCH SJC": load_var("var_garch_sjc_1.csv"),
    "Copula-GARCH Frank": load_var("var_garch_frank_1.csv"),
    "Copula-GARCH Gumbel": load_var("var_garch_gumbel_1.csv"),
    "Copula-GARCH Rotated Gumbel": load_var("var_garch_rotated_gumbel_1.csv"),
    "Copula-MSM Student": load_var("var_msm_student_1.csv"),
    #"Copula-MSM Gaussian": load_var("var_msm_gaussian_1.csv"),
    #"Copula-MSM Plackett": load_var("var_msm_plackett_1.csv"),
    #"Copula-MSM Clayton": load_var("var_msm_clayton_1.csv"),
    #"Copula-MSM Rotated Clayton": load_var("var_msm_rotated_clayton_1.csv"),
    #"Copula-MSM SJC": load_var("var_msm_sjc_1.csv"),
    #"Copula-MSM Frank": load_var("var_msm_frank_1.csv"),
    #"Copula-MSM Gumbel": load_var("var_msm_gumbel_1.csv"),
    #"Copula-MSM Rotated Gumbel": load_var("var_msm_rotated_gumbel_1.csv"),
}

var_panel_all_1 = concat_var_series(var_series_all_1)

var_panel_all_1.to_csv(VAR_OUTPUT_DIR / "var_panel_all_1.csv")
var_panel_all_1.head()

,Historical,Variance-Covariance,RiskMetrics,CCC-GARCH,Copula-GARCH Student,Copula-GARCH Gaussian,Copula-GARCH Plackett,Copula-GARCH Clayton,Copula-GARCH Rotated Clayton,Copula-GARCH SJC,Copula-GARCH Frank,Copula-GARCH Gumbel,Copula-GARCH Rotated Gumbel,Copula-MSM Student
2013-10-17,-3.211284,-2.614929,-2.702538,-2.266403,-2.268438,-2.266370,-2.208520,-2.288371,-1.970638,-2.275947,-2.124393,-2.221528,-2.285164,-2.595488
2013-10-18,-3.211284,-2.612849,-2.645782,-2.185638,-2.187684,-2.185600,-2.129779,-2.206803,-1.900353,-2.194750,-2.048471,-2.142452,-2.203715,-2.524178
2013-10-21,-3.211284,-2.612957,-2.625725,-2.175097,-2.177101,-2.175068,-2.119550,-2.196156,-1.891765,-2.184293,-2.036731,-2.132114,-2.193081,-2.567240
2013-10-22,-3.111556,-2.593221,-2.546125,-2.067385,-2.069479,-2.067397,-2.014603,-2.087758,-1.796775,-2.076445,-1.956249,-2.026223,-2.084802,-2.534799
2013-10-23,-3.111556,-2.590992,-2.479448,-1.985968,-1.987988,-1.985983,-1.934955,-2.005695,-1.724852,-1.994552,-1.867816,-1.946130,-2.002829,-2.442562

### 7.11 VaR 1% - Graph

In [11]:
fig4 = plot_var_forecasts(
    portfolio_returns=portfolio_ret_oos.rename("Portfolio returns"),
    var_forecasts=var_panel_fig_1,
    output_path=REPORTS_DIR / "figures" / "figure_4_var_1pct.html",
    title="Figure 4 — VaR forecasts at the 1% confidence level",
    positive_loss_var=False,
)

fig4.show()

In [12]:
fig4.write_image(
    REPORTS_DIR / "figures" / "figure_4_var_1pct.png",
    scale=2,
)

## 8. LR test

In [29]:
from src.risk import christoffersen_lr_test, var_exceedances
from src.var_v2 import portfolio_returns

def make_table_lr(returns, var_panel, alpha, weights=(0.5, 0.5)):
    rp = portfolio_returns(returns, weights)
    rp = rp.reindex(var_panel.index)

    rows = {}

    for model in var_panel.columns:
        hits = var_exceedances(rp, var_panel[model])
        test = christoffersen_lr_test(hits, alpha)

        rows[model] = {
            "EFV": hits.mean(),
            "uc": test["uc_pvalue"],
            "ind": test["ind_pvalue"],
            "cc": test["cc_pvalue"],
        }

    return pd.DataFrame(rows).T

In [41]:
def parse_model_name(model):
    if model in ["Historical", "RiskMetrics", "Variance-Covariance", "CCC-GARCH"]:
        group = "Bench"
        submodel = {
            "Historical": "Historical",
            "RiskMetrics": "RiskMetrics",
            "Variance-Covariance": "Var-Covar",
            "CCC-GARCH": "CCC-GARCH",
        }[model]
    elif model.startswith("Copula-GARCH"):
        group = "Copula-GARCH"
        submodel = model.replace("Copula-GARCH ", "")
    elif model.startswith("Copula-MSM"):
        group = "Copula-MSM"
        submodel = model.replace("Copula-MSM ", "")
    else:
        group = "Other"
        submodel = model

    submodel = submodel.replace("Gaussian", "Normal")
    submodel = submodel.replace("Rotated Clayton", "rotClayton")
    submodel = submodel.replace("Rotated Gumbel", "rotGumbel")

    return group, submodel

### 8.1 LR test: VaR 5% forecast

In [66]:
table_5 = make_table_lr(returns, var_panel_all, alpha=0.05)
table_5

                                EFV        uc       ind        cc
Historical                    0.036  0.131347  0.155388  0.116773
Variance-Covariance           0.040  0.288479  0.044012  0.074915
RiskMetrics                   0.072  0.033677  0.791915  0.101234
CCC-GARCH                     0.072  0.033677  0.678951  0.096215
Copula-GARCH Student          0.072  0.033677  0.678951  0.096215
Copula-GARCH Gaussian         0.072  0.033677  0.678951  0.096215
Copula-GARCH Plackett         0.072  0.033677  0.678951  0.096215
Copula-GARCH Clayton          0.070  0.052333  0.748039  0.144550
Copula-GARCH Rotated Clayton  0.076  0.012912  0.550230  0.038045
Copula-GARCH SJC              0.072  0.033677  0.678951  0.096215
Copula-GARCH Frank            0.070  0.052333  0.748039  0.144550
Copula-GARCH Gumbel           0.072  0.033677  0.678951  0.096215
Copula-GARCH Rotated Gumbel   0.070  0.052333  0.748039  0.144550
Copula-MSM Student            0.072  0.033677  0.678951  0.096215
Copula-MSM Gaussian           0.072  0.033677  0.678951  0.096215

In [ ]:
#table_5.to_csv(REPORTS_DIR / "tables" / "table_5_lr_var_5pct_raw.csv", index=True)

In [67]:
table_5 = table_5.reset_index().rename(columns={"index": "model"})
table_5

                           model    EFV        uc       ind        cc
0                     Historical  0.036  0.131347  0.155388  0.116773
1            Variance-Covariance  0.040  0.288479  0.044012  0.074915
2                    RiskMetrics  0.072  0.033677  0.791915  0.101234
3                      CCC-GARCH  0.072  0.033677  0.678951  0.096215
4           Copula-GARCH Student  0.072  0.033677  0.678951  0.096215
5          Copula-GARCH Gaussian  0.072  0.033677  0.678951  0.096215
6          Copula-GARCH Plackett  0.072  0.033677  0.678951  0.096215
7           Copula-GARCH Clayton  0.070  0.052333  0.748039  0.144550
8   Copula-GARCH Rotated Clayton  0.076  0.012912  0.550230  0.038045
9               Copula-GARCH SJC  0.072  0.033677  0.678951  0.096215
10            Copula-GARCH Frank  0.070  0.052333  0.748039  0.144550
11           Copula-GARCH Gumbel  0.072  0.033677  0.678951  0.096215
12   Copula-GARCH Rotated Gumbel  0.070  0.052333  0.748039  0.144550
13            Copula-MSM Student  0.072  0.033677  0.678951  0.096215
14           Copula-MSM Gaussian  0.072  0.033677  0.678951  0.096215

In [68]:
df_long = table_5.melt(
    id_vars="model",
    value_vars=["EFV", "uc", "ind", "cc"],
    var_name="stat",
    value_name="value"
)
df_long[["group", "submodel"]] = df_long["model"].apply(
    lambda x: pd.Series(parse_model_name(x))
)

table_5_formatted = df_long.pivot(
    index="stat",
    columns=["group", "submodel"],
    values="value"
)
table_5_formatted

group         Bench                                 Copula-GARCH            \
submodel Historical Var-Covar RiskMetrics CCC-GARCH      Student    Normal
stat
EFV        0.036000  0.040000    0.072000  0.072000     0.072000  0.072000
cc         0.116773  0.074915    0.101234  0.096215     0.096215  0.096215
ind        0.155388  0.044012    0.791915  0.678951     0.678951  0.678951
uc         0.131347  0.288479    0.033677  0.033677     0.033677  0.033677

group                                                                  \
submodel  Plackett   Clayton rotClayton       SJC     Frank    Gumbel
stat
EFV       0.072000  0.070000   0.076000  0.072000  0.070000  0.072000
cc        0.096215  0.144550   0.038045  0.096215  0.144550  0.096215
ind       0.678951  0.748039   0.550230  0.678951  0.748039  0.678951
uc        0.033677  0.052333   0.012912  0.033677  0.052333  0.033677

group              Copula-MSM
submodel rotGumbel    Student    Normal
stat
EFV       0.070000   0.072000  0.072000
cc        0.144550   0.096215  0.096215
ind       0.748039   0.678951  0.678951
uc        0.052333   0.033677  0.033677

In [69]:
stat_order = ["EFV", "uc", "ind", "cc"]
bench_order = ["Historical", "RiskMetrics", "Var-Covar", "CCC-GARCH"]
copula_order = [
    "Normal", "Student", "Plackett", "Clayton",
    "rotClayton", "SJC", "Frank", "Gumbel", "rotGumbel"
]
column_order = (
    [("Bench", c) for c in bench_order]
    + [("Copula-GARCH", c) for c in copula_order]
    + [("Copula-MSM", c) for c in copula_order[:2]]
)
table_5_formatted = table_5_formatted.reindex(index=stat_order, columns=pd.MultiIndex.from_tuples(column_order))
table_5_formatted = table_5_formatted.map(lambda x: f"{x:.3f}" if pd.notna(x) else "")
table_5_formatted

          Bench                                 Copula-GARCH                   \
     Historical RiskMetrics Var-Covar CCC-GARCH       Normal Student Plackett
stat
EFV       0.036       0.072     0.040     0.072        0.072   0.072    0.072
uc        0.131       0.034     0.288     0.034        0.034   0.034    0.034
ind       0.155       0.792     0.044     0.679        0.679   0.679    0.679
cc        0.117       0.101     0.075     0.096        0.096   0.096    0.096

                                                       Copula-MSM
     Clayton rotClayton    SJC  Frank Gumbel rotGumbel     Normal Student
stat
EFV    0.070      0.076  0.072  0.070  0.072     0.070      0.072   0.072
uc     0.052      0.013  0.034  0.052  0.034     0.052      0.034   0.034
ind    0.748      0.550  0.679  0.748  0.679     0.748      0.679   0.679
cc     0.145      0.038  0.096  0.145  0.096     0.145      0.096   0.096

In [ ]:
# table_5_formatted.to_csv(
#     REPORTS_DIR / "tables" / "table_5_lr_var_5pct_formatted.csv",
#     index=True,
#     encoding="utf-8-sig"
# )

In [65]:
table_5_formatted = pd.read_csv(REPORTS_DIR / "tables" / "table_5_lr_var_5pct_formatted.csv", header=[0, 1],
    index_col=0
)
table_5_formatted

          Bench                                 Copula-GARCH                   \
     Historical RiskMetrics Var-Covar CCC-GARCH       Normal Student Plackett
stat
EFV       0.036       0.072     0.040     0.072        0.072   0.072    0.072
uc        0.131       0.034     0.288     0.034        0.034   0.034    0.034
ind       0.155       0.792     0.044     0.679        0.679   0.679    0.679
cc        0.117       0.101     0.075     0.096        0.096   0.096    0.096

                                                       Copula-MSM
     Clayton rotClayton    SJC  Frank Gumbel rotGumbel     Normal Student
stat
EFV    0.070      0.076  0.072  0.070  0.072     0.070      0.072   0.072
uc     0.052      0.013  0.034  0.052  0.034     0.052      0.034   0.034
ind    0.748      0.550  0.679  0.748  0.679     0.748      0.679   0.679
cc     0.145      0.038  0.096  0.145  0.096     0.145      0.096   0.096

In [ ]:
latex = table_5_formatted.to_latex(
    index=True,
    multicolumn=True,
    multicolumn_format="c",
    multirow=False,
    escape=False,
    caption="The results of LR test using VaR(5%) forecasts.",
    label="tab:lr_var_5",
)

with open(REPORTS_DIR / "tables" / "table_5_lr_var_5pct.tex", "w", encoding="utf-8") as f:
    f.write(latex)

### 8.2 LR test: VaR 1% forecast

In [79]:
table_6 = make_table_lr(returns, var_panel_all_1, alpha=0.01)
table_6

                                EFV            uc       ind            cc
Historical                    0.008  6.414349e-01  0.019432  5.845258e-02
Variance-Covariance           0.014  3.965697e-01  0.002146  6.286847e-03
RiskMetrics                   0.032  8.395385e-05  0.096153  1.097107e-04
CCC-GARCH                     0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Student          0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Gaussian         0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Plackett         0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Clayton          0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Rotated Clayton  0.046  3.540639e-09  0.388719  1.856326e-08
Copula-GARCH SJC              0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Frank            0.036  6.095229e-06  0.155388  1.316035e-05
Copula-GARCH Gumbel           0.030  2.857199e-04  0.073289  2.788692e-04
Copula-GARCH Rotated Gumbel   0.030  2.857199e-04  0.073289  2.788692e-04
Copula-MSM Student            0.014  3.965697e-01  0.002146  6.286847e-03

In [72]:
table_6.to_csv(REPORTS_DIR / "tables" / "table_6_lr_var_1pct_raw.csv")

In [80]:
table_6 = table_6.reset_index().rename(columns={"index": "model"})

df_long = table_6.melt(
    id_vars="model",
    value_vars=["EFV", "uc", "ind", "cc"],
    var_name="stat",
    value_name="value"
)
df_long[["group", "submodel"]] = df_long["model"].apply(
    lambda x: pd.Series(parse_model_name(x))
)
table_6_formatted = df_long.pivot(
    index="stat",
    columns=["group", "submodel"],
    values="value"
)

column_order = (
    [("Bench", c) for c in bench_order]
    + [("Copula-GARCH", c) for c in copula_order]
    + [("Copula-MSM", "Student")]
)
table_6_formatted = table_6_formatted.reindex(index=stat_order, columns=pd.MultiIndex.from_tuples(column_order))
table_6_formatted = table_6_formatted.map(lambda x: f"{x:.3f}" if pd.notna(x) else "")
table_6_formatted

          Bench                                 Copula-GARCH                   \
     Historical RiskMetrics Var-Covar CCC-GARCH       Normal Student Plackett
stat
EFV       0.008       0.032     0.014     0.030        0.030   0.030    0.030
uc        0.641       0.000     0.397     0.000        0.000   0.000    0.000
ind       0.019       0.096     0.002     0.073        0.073   0.073    0.073
cc        0.058       0.000     0.006     0.000        0.000   0.000    0.000

                                                       Copula-MSM
     Clayton rotClayton    SJC  Frank Gumbel rotGumbel    Student
stat
EFV    0.030      0.046  0.030  0.036  0.030     0.030      0.014
uc     0.000      0.000  0.000  0.000  0.000     0.000      0.397
ind    0.073      0.389  0.073  0.155  0.073     0.073      0.002
cc     0.000      0.000  0.000  0.000  0.000     0.000      0.006

In [ ]:
# table_6_formatted.to_csv(
#     REPORTS_DIR / "tables" / "table_6_lr_var_1pct_formatted.csv",
#     index=True,
#     encoding="utf-8-sig"
# )

In [ ]:
table_6_formatted = pd.read_csv(REPORTS_DIR / "tables" / "table_6_lr_var_1pct_formatted.csv", header=[0, 1],
    index_col=0
)

In [82]:
latex = table_6_formatted.to_latex(
    index=True,
    multicolumn=True,
    multicolumn_format="c",
    multirow=False,
    escape=False,
    caption="The results of LR test using VaR(1%) forecasts.",
    label="tab:lr_var_1",
)

with open(REPORTS_DIR / "tables" / "table_6_lr_var_1pct.tex", "w", encoding="utf-8") as f:
    f.write(latex)

## OLD VaR

### Pre-backtest

In [129]:
hits_5pct = var_exceedances(
    returns=portfolio_oos,
    var_forecasts=var_forecasts["Student-Copula-MSM VaR 5%"],
)
hits_1pct = var_exceedances(
    returns=portfolio_oos,
    var_forecasts=var_forecasts["Student-Copula-MSM VaR 1%"],
)

pre_backtest_summary = pd.DataFrame(
    {
        "alpha": [0.05, 0.01],
        "nobs": [len(hits_5pct), len(hits_1pct)],
        "violations": [hits_5pct.sum(), hits_1pct.sum()],
        "efv": [hits_5pct.mean(), hits_1pct.mean()],
    },
    index=["VaR 5%", "VaR 1%"],
)

pre_backtest_summary

        alpha  nobs  violations    efv
VaR 5%   0.05   500          35  0.070
VaR 1%   0.01   500           6  0.012